### ISSUE TITLE
Support for dev-kit that has an Adreno 640

### ISSUE THREAD

**Issue by nishinkvasu** [google/agi#1005]
I am working with a Qualcomm dev kit that has the Adreno 640 GPU. Would there be any way to get the AGI working on this device, since the GPU is a supported one?

**Comment by davie504** [comment]
Intesting in this too. But I'm sure they can't do it because they want to sold more pixel devices

**Comment by ttanatb** [comment]
This is a trickier use case and is not one we plan to support. I would suggest looking into vendor-specific products for this use case as it is a little bit more niche.

In theory, it might work, but it depends on wether the GPU driver itself is able to provide AGI with the information it needs (i.e. GPU counters). However, I don't know all the differences between a dev-kit or retail device and cannot guarantee that it will work or continue to work with subsequent releases of AGI.
