### ISSUE TITLE
[Frame Profile]how to capture more than one frame？

### ISSUE THREAD

**Issue by linxs0211** [google/agi#1006]
hi,
    Currently, we are  trying to use AGI instead of GAPID(due to Macos upgrading to Monterey..) to analyze GPU related stuffs. 
    But  only a single frame can be captured when using Frame Proflier...
    
    I am not sure if AGI only can capture a single frame  or it's just a feature that will be supported later?

     ![image](https://user-images.githubusercontent.com/55836257/147529954-59981241-6b3c-4490-bb6b-271bf158235f.png)

   Thanks.

**Comment by alecazam** [comment]
Only the system profile displays across multiple frames.  This is indeed limiting for us, and having to relaunch the app to capture another frame or after changing app state is quite limiting.

**Comment by mikes-lunarg** [comment]
Have you tried the `--max-frames` option listed under `agi --fullhelp`?

**Comment by alecazam** [comment]
That doesn't work for our use case, but might for the original poster.  I reported this a while ago here.  https://github.com/google/agi/issues/920  We need to be able to load the game which takes some time, then load a level, then do a capture, the review it, then load another part of the level, then do a second capture, repeat.  Having to relaunch the app every time is limiting.  RenderDoc at least splits off capture analysis to another app, and then one can return back to the running app to capture again.  But RenderDoc doesn't deal with profiling or trace capture.

**Comment by pmuetschard** [comment]
AGI is intended to be a single frame capture tool, using `--max-frames` will put you in unsupported territory, which is why it's not listed for `--help`, and the option may go away in the future.

The issue alluded to [above](https://github.com/google/agi/issues/1006#issuecomment-1009491040) is tracked separately and something we're aware of and on our future roadmap.
