### ISSUE TITLE
Frame Profile : "Initializing"  after click start trace and can not start capture trace. I notice the application is relaunched.

### ISSUE THREAD

**Issue by Ed1sonzZ** [google/agi#1007]
**Environment information:**
 - AGI version:
 - Host OS: [e.g. Linux]
 If tracing on Android:
 - Device model:
 - Android Version:

**Bug description**

**Reproduction steps**

**Stacktrace**
Please paste a stacktrace here if it's available.

**Screenshots**

**Additional debugging information**
- Please attach the generated _gapis.log_ and _gapic.log_ files you will find in the temp folder (e.g. /tmp/ on linux).
- If using Android: Please attach a full logcat dump (```adb logcat -d > logcat-full.txt```) that contains logs since AGI was started.

**Comment by t1u1** [comment]
Same here.

AGI version: 2.1.0
Device: Pixel 4a
Android: 12, Build number SQ1A.220105.002

System trace works, but Frame trace using OpenGL + ANGLE is stuck in "Initializing" state.

Angle version: 15789_angle-arm_64.apk

**Comment by t1u1** [comment]
In the logcat of the device, this message is repeated continuously while AGI is active:
```
failed to connect to socket 'localabstract:gapii': could not connect to localabstract address 'localabstract:gapii'
```

**Comment by ttanatb** [comment]
Hi, thanks for filing the issue (and apologies for the untimely response) -- there's some scenarios in which AGI silently fails without the best information for how to triage, and we're working to improve this.

One likely scenario occurs when the application launches multiple processes and AGI mistakenly attaches itself to a process that does not make draw calls, leaving the phone at a blank screen. In that case, add the exact process name in the trace dialog (seen below), and AGI will attach itself to the correct process.
![image](https://user-images.githubusercontent.com/14023901/174629908-704b0e16-5563-47d2-95ee-acd8dfd83d0d.png)

If this is not the issue you're encountering, then please provide more context / logs that will help me triage and figure out what's going on :)

**Comment by hillli007** [comment]
@ttanatb I have the same problem,  and my scenario is not multiple processes. Has the problem been solved?

**Comment by ttanatb** [comment]
We've seen issues with Frame Profiling not working against specific applications, but this is often a case by case basis. @hillli007 Please feel free to open a new issue (or re-open this) with more information, context, logs. (`gapis.log` `gapic.log` and result from `adb logcat -d > logcat-full.txt`)
