### ISSUE TITLE
Can not detect the onplus 9R device

### ISSUE THREAD

**Issue by shongbee2** [google/agi#1010]
**Environment information:**
 - AGI version:
 - Host OS: [e.g. Linux]
 If tracing on Android:
 - Device model:
 - Android Version:

**Bug description**
I have connected the Oneplus 9r to the computer via a USB cable， but the android GPU inspector can't find it.
I closed other process, restart computer, re connenct the device vie a USB cable, it dons't work also.
but  andorid studio can find the device.

**Reproduction steps**
1.restart the computer
2.connect oneplus 9r to the computer via a usb cable (the device is debugable)
3.open android gpu inspector
4.capture a new trace
5.the device list can't find the device

**Stacktrace**
Please paste a stacktrace here if it's available.

**Screenshots**

**Additional debugging information**
- Please attach the generated _gapis.log_ and _gapic.log_ files you will find in the temp folder (e.g. /tmp/ on linux).
- If using Android: Please attach a full logcat dump (```adb logcat -d > logcat-full.txt```) that contains logs since AGI was started.

**Comment by ttanatb** [comment]
Thanks for filing the issue, can you see if the device shows up when you call `adb devices -l`? It's weird that it would show up on Android Studio, but not on AGI -- AGI takes a moment to find the device, especially if you had just attached it.

It's possible that there is an underlying cause elsewhere (e.g. bad installation), please let me know if you're still running into this issue and I can help triage.

**Comment by JWhiteCat** [comment]
I have the same problem

**Comment by ttanatb** [comment]
@JWhiteCat Thanks for commenting on this, could you check if your device shows up when you call `adb devices -l`? If it does show up using the `adb` command but not with AGI, then AGI is having trouble collecting the data it needs (and we're working to make this error more obvious and actionable).

If your device does not show up with `adb devices -l` then please make sure that your USB cable is not faulty and that your device has USB debugging enabled.

If your device shows up with the `adb` command and not with AGI, please attach the log files `gapic.log` and `gapis.log` from your tmp directory (this can be access through the top menu on AGI `Help > Open Log Directory`). Additionally, please also include a full logcat dump `adb logcat -d > logcat-full.txt`

![Screen Shot 2022-07-26 at 11 05 37 AM](https://user-images.githubusercontent.com/14023901/180980992-e718b3ed-5b88-4211-a5d4-ed082d41c90c.png)

**Comment by ttanatb** [comment]
Closing this due to staleness
