### ISSUE TITLE
Samsung Galaxy S21 support validation failed with latest AGI version

### ISSUE THREAD

**Issue by ramcn** [google/agi#1023]
**Environment information:**
 - AGI version: Version 2022-2.2.0:dev-20220120-136277d9c2ca5d416c38f41f2c376fd820848ecb
 - Host OS: Windows
 If tracing on Android:
 - Device model: Samsung S21
 - Android Version: 11

**Bug description**
Device support validation failed with latest AGI

**Reproduction steps**
Device validation

**Screenshots**
![s21-ss](https://user-images.githubusercontent.com/2152628/151694525-917edf0f-1fc8-421b-9071-a3d3fddfceec.png)

**Debug info**
adb shell getprop ro.build.fingerprint
samsung/t2sxxx/t2s:11/RP1A.200720.012/G996BXXU1ATLD:user/release-keys

$ ./gapit.exe -log-level Fatal devices -os android | grep driver_version
                "driver_version": 109051904,

**Comment by ttanatb** [comment]
Hello, thanks for reporting this issue. Could you try validating with the newest release? It has more UI that'll help us triage what's going on here.

**Comment by ttanatb** [comment]
Closing this for now due to inactivity, if you're still facing validation issues please re-open
