### ISSUE TITLE
Support capturing via GLSurfaceView

### ISSUE THREAD

**Issue by nmr8acme** [google/agi#1039]
**Environment information:**
 - AGI version: 2.1.0
 - Host OS: [e.g. Linux] OSX 12.1
 If tracing on Android:
 - Device model: Pixel 4a
 - Android Version: 12

**Bug description**
GLSurfaceView frame not captured. Instead, the Android UI framework's frame is captured. Note that in the screenshot provided the Android UI framework is rendered, but the contents of the GLSurfaceView are not. I'm interested in the GLSurfaceView.

**Reproduction steps**
Capture a frame using OpenGL on ANGLE of an app with native Android UI and also GL in a GLSurfaceView, e.g. MyRadar.

**Stacktrace**
n/a

**Screenshots**
<img width="1496" alt="image" src="https://user-images.githubusercontent.com/5373573/153652367-13803056-8efb-46af-85bc-6f79fb7991d1.png">

**Additional debugging information**
Available on request

**Comment by ttanatb** [comment]
Hi, thanks for creating this issue -- unfortunately this is not a supported workflow and we wouldn't be able to prioritize work to implement this. Are you instead able to utilize System Profiling to measure performance or RenderDoc to debug your issue?
