### ISSUE TITLE
Google Pixel 4 XL support validation failed

### ISSUE THREAD

**Issue by Kelvin377** [google/agi#1043]
Environment information:

AGI version: Version 2021-2.1.0

Host OS: Win 10
If tracing on Android:
Device model: Google Pixel 4 XL
Android Version: 11
GPU: Qualcomm Adreno 640
Bug description
device support validation failed

**Bug description**

**Reproduction steps**

**Stacktrace**
Please paste a stacktrace here if it's available.

**Screenshots**

**Additional debugging information**
- Please attach the generated _gapis.log_ and _gapic.log_ files you will find in the temp folder (e.g. /tmp/ on linux).
- If using Android: Please attach a full logcat dump (```adb logcat -d > logcat-full.txt```) that contains logs since AGI was started.

[gapis.log](https://github.com/google/agi/files/8107869/gapis.log)
[gapic.log](https://github.com/google/agi/files/8107870/gapic.log

)

**Comment by ttanatb** [comment]
Hi, thank you for reporting this, could you try this again with the latest release. There's more UI there to help us triage these issues.
