### ISSUE TITLE
Please, do support for LG Velvet

### ISSUE THREAD

**Issue by someWhereInEarth** [google/agi#1044]
Maker : LG
Model : VELVET
Chipset : Qualcomm SM7250 Snapdragon 765G 5G (7 nm)
GPU : Adreno 620
OS : Android 10

**Comment by ttanatb** [comment]
Hi, thanks for filing this issue. Unfortunately, device support is a fairly involved process which requires a non-trivial amount of work from our partners. Getting AGI profiling support for an older phone is an even more involved process and is out-of-scope for device support requests.
