### ISSUE TITLE
Consistent Replay Crashes after taking Frame Profile (OpenGL on ANGLE)

### ISSUE THREAD

**Issue by astreet** [google/agi#1069]
**Environment information:**
 - AGI version: 2022-3.0.0
 - Host OS: Mac OS 12.2.1
 If tracing on Android:
 - Device model: Pixel 5
 - Android Version: 12
 - AGI ANGLE APK Version: https://agi-angle.storage.googleapis.com/97.0.4689.3/17153_angle-arm_64.apk

**Bug description**

When taking Frame Profiles, the trace seems to be taken correctly however the analysis pane fails to be able to render anything in the frame buffer or give any performance info on any commands. All panes show some variation of 'Failed to profile the replay. Cause: Replay crash' or 'Couldn't get framebuffer attachment: Replay crash'.

I'm not sure where to pull logs about the crash, but I do see my app being restarted a few times. In logcat, potentially relevant lines:

```
03-24 13:14:43.371 29898 29917 E Adreno-AppProfiles: Could not find QSPM HAL service
03-24 13:14:43.685 29898 29942 E GAPID   : gapir [bazel-out/android-arm64-v8a-opt/bin/gapir/cc/vulkan_gfx_api.cpp:2948] Attempted to call unsupported function vkGetInstanceProcAddr
03-24 13:14:43.716 29898 29942 E Adreno-AppProfiles: Could not find QSPM HAL service
03-24 13:14:43.950   643   643 E BpTransactionCompletedListener: Failed to transact (-32)
03-24 13:14:43.954  1342  1342 E adbd    : failed to connect to socket 'localfilesystem:/data/user/0/com.google.android.gapid.arm64v8a/files/gapir-socket': could not connect to localfilesystem address 'localfilesystem:/data/user/0/com.google.android.gapid.arm64v8a/files/gapir-socket'
03-24 13:14:44.958  1342  1342 E adbd    : failed to connect to socket 'localfilesystem:/data/user/0/com.google.android.gapid.arm64v8a/files/gapir-socket': could not connect to localfilesystem address 'localfilesystem:/data/user/0/com.google.android.gapid.arm64v8a/files/gapir-socket'
```

I created a really simple Android app -- basically just the default project -- so nothing too interesting there but I can attach the code for it if helpful.

I'm trying to get started with AGI so apologies if this is in the wrong place or answered somewhere - I couldn't find it if it is. Please let me know if there's anything I can do on my end to fix this, or more info I can provide!

**Reproduction steps**
Take a Frame Profile - OpenGL on ANGLE trace

**Stacktrace**
See logcat info above

**Screenshots**
![Screen Shot 2022-03-24 at 13 16 09](https://user-images.githubusercontent.com/594924/159924200-38bf2d95-8ebf-4a96-b6db-04f29fa94b28.png)

**Additional debugging information**
- Please attach the generated _gapis.log_ and _gapic.log_ files you will find in the temp folder (e.g. /tmp/ on linux).
- If using Android: Please attach a full logcat dump (```adb logcat -d > logcat-full.txt```) that contains logs since AGI was started. - I've tried to pull relevant logs since this is my personal device. Let me know if you think I may be missing some.

[com.example.porterdufftest_angle_20220324_1310.gfxtrace.zip](https://github.com/google/agi/files/8341730/com.example.porterdufftest_angle_20220324_1310.gfxtrace.zip)

**Comment by pmuetschard** [comment]
Thank you for the detailed bug report and sorry for the long delay. Unfortunately this was flying under the radar for a while. With #1084 I can now replay the attached trace.
