### ISSUE TITLE
Samsung Galaxy S10 (GM-973F) validation fails

### ISSUE THREAD

**Issue by emilienregent** [google/agi#1075]
**Environment information:**
 - AGI version: 2022-3.0.0
 - Host OS: Windows 10
 If tracing on Android:
 - Device model: GM-G973F
 - Android Version: 11

**Bug description**
Validation fails for device SG S10.

**Reproduction steps**
Steps to reproduce the behavior: Plug the device, start AGI and see the validation failing.

**Screenshots**
![image](https://user-images.githubusercontent.com/2046681/162174371-fe994261-c203-4285-968f-d9681a8e92a6.png)

**Additional debugging information**

- ` ./gapit -log-level Fatal devices -os android | grep driver_version`  "driver_version": 109051904
- `adb shell getprop ro.build.fingerprint` samsung/beyond1lteeea/beyond1:11/RP1A.200720.012/G973FXXU9EUA4:user/release-keys

**Comment by ttanatb** [comment]
Hi, could you provide the logcat from `adb logcat > logcat.txt` to help make it easier to triage what's going on?

**Comment by ttanatb** [comment]
This error is likely happening if you are using an unsupported device or if you're running a custom OS. Please feel free to re-open this issue if this is not the case and we can triage further.
