### ISSUE TITLE
E: <gapis> Couldn't scan devices:     Cause: FUCHSIA_FFX_PATH is not set. The "ffx" tool, from the Fuchsia SDK, is required for Fuchsia device profiling.

### ISSUE THREAD

**Issue by Iapa** [google/agi#1085]
**Environment information:**
 - AGI version:
 - Host OS: [e.g. Linux]
 If tracing on Android:
 - Device model:
 - Android Version:

**Bug description**

**Reproduction steps**

**Stacktrace**
Please paste a stacktrace here if it's available.

**Screenshots**
![IMfvgIiogO](https://user-images.githubusercontent.com/15715584/163845515-d2ce5688-c8d0-4c06-92e4-63b6b5466d28.png)

**Additional debugging information**
- Please attach the generated _gapis.log_ and _gapic.log_ files you will find in the temp folder (e.g. /tmp/ on linux).
- If using Android: Please attach a full logcat dump (```adb logcat -d > logcat-full.txt```) that contains logs since AGI was started.

**Comment by pmuetschard** [comment]
That message can be ignored if working on Android. The AOSP images do not support profiling and therefore not be used with AGI.
