### ISSUE TITLE
Pixel4 validation failed

### ISSUE THREAD

**Issue by galis** [google/agi#1086]
**Environment information:**
 - AGI version:3.0.0
 - Host OS: Mac Os 10.15.6
 - Device model:Pixel4 standard
 - Android Version:Android 11

**Bug description**
Device support but not validation.

**Stacktrace**
Please paste a stacktrace here if it's available.

**Screenshots**
![截屏2022-04-20 16 35 30](https://user-images.githubusercontent.com/6220187/164187402-3b74ef93-0d93-4029-abd9-b42f142835c6.png)

**Additional debugging information**
-I make the eng aosp Android 11, flush the pixel4.Is this cause the  problem?

**Comment by galis** [comment]
build_print:Android/aosp_flame/flame:11/RQ2A.210505.002/galis07271354:userdebug/test-keys

**Comment by lpy** [comment]
You need to flash back to the public build instead of the AOSP build.
