### ISSUE TITLE
Can AGI be used to profile WebGL application inside the browser?

### ISSUE THREAD

**Issue by mvaligursky** [google/agi#1109]
**Environment information:**
 - AGI version:Version 2022-3.0.1
 - Host OS: [e.g. Linux] macOS 12.3.1
 If tracing on Android:
 - Device model: Pixel 6
 - Android Version: 12

I am interested in using AGI to capture a frame of WebGl running inside a browser. When trying to use Chrome on Android, the device validation passes, but I fail to capture any commands using either ANGLE or Vulkan, with or without buffering. It's possible this is due to the browser not having 'debugging' in its android manifest, but I'm not sure.

Is there some way to accomplish this? It would be amazing to profile WebGl applications on device.
I also tried building custom browser based on https://github.com/alandau/sweb but this does not allow webgl content to run for some reason (webgl not available).

**Comment by mvaligursky** [comment]
@kenrussell Would you have any ideas on this?

**Comment by ttanatb** [comment]
Hi, thanks for filing this issue. Unfortunately this use case is a little bit more ambitious than what we currently support. Is it possible to instead look at options for profiling WebGL directly?

**Comment by mvaligursky** [comment]
Hi .. thanks for the response. I have not found any tools that can profile GPU side of the WebGl reliably on the Android platform, and so I've created this ticket to see if AGI can fill the gap.

I'll keep looking in the meantime!

**Comment by vonture** [comment]
I suspect this is because AGI is not capturing all of Chrome's processes. WebGL and other rendering commands are forwarded to Chrome's GPU process which then makes the final OpenGL or Vulkan calls.

I'm not familiar with AGI enough to know if it has a "capture child processes" option like renderdoc but that may be necessary to capture WebGL on Android.

**Comment by ttanatb** [comment]
Closing this issue for now -- adding functionality to profile WebGL applications inside the browser is not a usecase we have the bandwidth to explore
