### ISSUE TITLE
Documentation problem

### ISSUE THREAD

**Issue by LichKing-2234** [google/agi#1114]
[On this page](https://gpuinspector.dev/validation)...

The link is named `https://developer.android.com/agi`, but link to `https://gpuinspector.dev/validation`

**Comment by ttanatb** [comment]
Thanks for filing this issue!

For now, the validation page has moved to https://developer.android.com/agi/supported-devices and we're working to fix the wrong link.

**Comment by ttanatb** [comment]
Fixed in https://github.com/google/agi/pull/1118
