### ISSUE TITLE
Device connect failed ——Samsung S20 

### ISSUE THREAD

**Issue by chimppppp** [google/agi#1131]
**Environment information:**
 - AGI version:3.0.1
 - Host OS: Win10
 If tracing on Android:
 - Device model: Samsung S20
 - Android Version: Android12

**Bug description**
I have successfully connected with Samsung S20 before. but now i cant connect again. it show no device connected that supports this trace type.

**Screenshots**
![impicture_20220622_144357](https://user-images.githubusercontent.com/51081464/174961616-dae1878d-2998-4674-bfad-1a1a4616ae2c.png)

**Additional debugging information**
==========here is the log===========
06:32:08.780 I: <gapis> Adding new device
06:32:08.780 I: <gapis> New trace scheduler for device: e3a0401e51258690cd224d772ff2bfc23cb62bd1 DESKTOP-P04479O
06:32:08.780 I: <gapis> New scheduler for device: e3a0401e51258690cd224d772ff2bfc23cb62bd1
06:32:08.790 I: <gapis> Starting grpc server
06:32:08.895 E: <gapis> Couldn't scan devices: Cannot get device information
06:32:27.623 I: [Try ABI: arm64-v8a⇒gapidapk.EnsureInstalled] <gapis> Examining gapid.apk on host...
06:32:27.627 I: [Try ABI: arm64-v8a⇒gapidapk.EnsureInstalled] <gapis> Looking for gapid.apk...
06:32:27.828 I: [Try ABI: arm64-v8a⇒gapidapk.EnsureInstalled] <gapis> Found gapid package...
06:32:28.049 I: <gapis> No developer driver found, attempting to use GPU profiling libraries in system image.
06:32:28.831 I: <gapis> [launch producer] I: Trying libgpudataproducer.so
06:32:28.840 I: <gapis> [launch producer] I: Calling start at 0x72512b5c9c
06:32:28.841 I: <gapis> [launch producer] QPerfettoCountersDataPro QProfilerInterface: Initializing (v2020.6, built Oct  7 2021@17:10:54)...
06:32:28.880 I: <gapis> [launch producer] QPerfettoCountersDataPro gpu.counters: Starting tracing thread
06:32:28.882 I: <gapis> [launch producer] perfetto.cc:39641        Producer connected
06:32:28.968 I: <gapis> [launch producer] QPerfettoCountersDataPro Start counter trace returned 0
06:32:29.845 I: [startDevInfoService] <gapis> Attempt to start service: com.google.android.gapid.DeviceInfoService
06:32:30.018 I: [startDevInfoService] <gapis> Attempt to start service: com.google.android.gapid.DeviceInfoService
06:32:30.190 I: [startDevInfoService] <gapis> Attempt to start service: com.google.android.gapid.DeviceInfoService
06:32:33.955 I: [Try ABI: arm64-v8a⇒gapidapk.EnsureInstalled] <gapis> Examining gapid.apk on host...
06:32:33.959 I: [Try ABI: arm64-v8a⇒gapidapk.EnsureInstalled] <gapis> Looking for gapid.apk...
06:32:34.142 I: [Try ABI: arm64-v8a⇒gapidapk.EnsureInstalled] <gapis> Found gapid package...
06:32:34.380 I: <gapis> No developer driver found, attempting to use GPU profiling libraries in system image.
06:32:34.772 I: <gapis> [launch producer] Exit.
06:32:34.772 E: <gapis> [EnsurePerfettoProducerLaunched] error: exit status 143
06:32:35.109 I: <gapis> [launch producer] I: Trying libgpudataproducer.so
06:32:35.109 I: <gapis> [launch producer] I: Calling start at 0x7ae4070c9c
06:32:35.109 I: <gapis> [launch producer] QPerfettoCountersDataPro QProfilerInterface: Initializing (v2020.6, built Oct  7 2021@17:10:54)...
06:32:35.135 I: <gapis> [launch producer] QPerfettoCountersDataPro gpu.counters: Starting tracing thread
06:32:35.138 I: <gapis> [launch producer] perfetto.cc:39641        Producer connected
06:32:35.226 I: <gapis> [launch producer] QPerfettoCountersDataPro Start counter trace returned 0
06:32:36.111 I: [startDevInfoService] <gapis> Attempt to start service: com.google.android.gapid.DeviceInfoService
06:32:36.269 I: [startDevInfoService] <gapis> Attempt to start service: com.google.android.gapid.DeviceInfoService
06:32:36.442 I: [startDevInfoService] <gapis> Attempt to start service: com.google.android.gapid.DeviceInfoService
06:32:40.210 I: [Try ABI: arm64-v8a⇒gapidapk.EnsureInstalled] <gapis> Examining gapid.apk on host...
06:32:40.215 I: [Try ABI: arm64-v8a⇒gapidapk.EnsureInstalled] <gapis> Looking for gapid.apk...
06:32:40.445 I: [Try ABI: arm64-v8a⇒gapidapk.EnsureInstalled] <gapis> Found gapid package...
06:32:40.709 I: <gapis> No developer driver found, attempting to use GPU profiling libraries in system image.
06:32:41.102 I: <gapis> [launch producer] Exit.
06:32:41.102 E: <gapis> [EnsurePerfettoProducerLaunched] error: exit status 143

**Comment by chimppppp** [comment]
GPU is Adreno
Here are something what I have done，maybe that make it hapen.
I am going to testing FrameProfile - Vulkan, but it suck in capturing.
![impicture_20220622_194629](https://user-images.githubusercontent.com/51081464/175021624-882b579f-c4c3-4aa8-8a7b-8fbdf58f49a0.png)
and I click cancel, after that it can not connect to my device any more.
（That's what I remember，There may be other reasons）
[Samsung-S20.zip](https://github.com/google/agi/files/8957231/Samsung-S20.zip)

**Comment by ttanatb** [comment]
I know that there's a known issue with Samsung devices with Adreno GPUs https://github.com/google/agi/issues/1113 -- unsure if this is the same issue (would need to investigate further)

**Comment by ttanatb** [comment]
Could you try the workaround in https://github.com/google/agi/issues/1113#issuecomment-1165786744 and see if it fixes your problem?

**Comment by chimppppp** [comment]
this file not exist on my device. If this is normal，but my device have no permission to create the file...
`/sys/class/kgsl/kgsl-3d0/perfcounter`

**Comment by ttanatb** [comment]
Sorry for the delay, but could you run `adb shell getprop ro.build.product` and see what gets returned?

**Comment by ttanatb** [comment]
I fixed a similar issue in this dev release https://github.com/google/agi-dev-releases/releases/tag/v3.1.0-dev-20220811 let me know if the device is still not showing up on the drop down
