### ISSUE TITLE
virtual_swapchain creates a command pool for each image, but only deallocates one command pool

### ISSUE THREAD

**Issue by bizehao** [google/agi#1135]
**Environment information:**
 - AGI version:
 - Host OS: [e.g. Linux]
 If tracing on Android:
 - Device model:
 - Android Version:

**Bug description**

[    EXPECT_SUCCESS(functions_->vkCreateCommandPool(device_, &command_pool_info,](https://github.com/google/agi/blob/318c98a63d9ea0a34eb845068a25fe83c466cd50/core/vulkan/vk_virtual_swapchain/cc/virtual_swapchain.cpp#L149)

This piece of code will cause memory leaks

This will be created once in each loop. It will only be released once when destructing. It should only be created once outside

```
build_swapchain_image_data_ ->EXPECT_SUCCESS(functions_->vkCreateCommandPool(device_, &command_pool_info, pAllocator, &command_pool_));

for (uint32_t i = 0; i < num_images_; i++) {
    image_data_[i] = build_swapchain_image_data_();
    free_images_.push_back(i);
}
```

**Reproduction steps**

**Stacktrace**
Please paste a stacktrace here if it's available.

**Screenshots**

**Additional debugging information**
- Please attach the generated _gapis.log_ and _gapic.log_ files you will find in the temp folder (e.g. /tmp/ on linux).
- If using Android: Please attach a full logcat dump (```adb logcat -d > logcat-full.txt```) that contains logs since AGI was started.

**Comment by ttanatb** [comment]
Thanks for the catch and for reporting this, it looks like `vkCreateCommandPool` should be called outside of the `build_swapchain_image_data_` lambda to match the de-allocation pattern in [Destroy](https://github.com/google/agi/blob/master/core/vulkan/vk_virtual_swapchain/cc/virtual_swapchain.cpp#L333).

We'll try to prioritize this and get this in for the next release :)
