### ISSUE TITLE
Build failure with grpc dependency on Ubuntu 18.04

### ISSUE THREAD

**Issue by dfriederich** [google/agi#1152]
**Environment information:**
 - AGI version: v.3.0.1 (same failure on master)
 - Host OS: Ubuntu 18.04.5 LTS

**Bug description**
Build failure for running
> bazel build pkg
`ERROR: /home/dfriederich/.cache/bazel/_bazel_dfriederich/00df44614fe47960f557631775374dc9/external/org_golang_google_grpc/BUILD.bazel:3:11: GoCompilePkg external/org_golang_google_grpc/grpc.a failed: (Exit 1): builder failed: error executing command 
  (cd /home/dfriederich/.cache/bazel/_bazel_dfriederich/00df44614fe47960f557631775374dc9/sandbox/linux-sandbox/33886/execroot/gapid && \
  exec env - \
    CGO_ENABLED=1 \
    GOARCH=amd64 \
    GOOS=linux \
    GOPATH='' \
    GOROOT=external/go_sdk \
    GOROOT_FINAL=GOROOT \
    PATH=/usr/bin:/bin \
  bazel-out/host/bin/external/go_sdk/builder compilepkg -sdk .....)
Execution platform: @local_config_platform//:host

Use --sandbox_debug to see verbose messages from the sandbox
compilepkg: missing strict dependencies:
	/home/dfriederich/.cache/bazel/_bazel_dfriederich/00df44614fe47960f557631775374dc9/sandbox/linux-sandbox/33886/execroot/gapid/external/org_golang_google_grpc/server.go: import of "golang.org/x/net/trace"
	/home/dfriederich/.cache/bazel/_bazel_dfriederich/00df44614fe47960f557631775374dc9/sandbox/linux-sandbox/33886/execroot/gapid/external/org_golang_google_grpc/stream.go: import of "golang.org/x/net/trace"
	/home/dfriederich/.cache/bazel/_bazel_dfriederich/00df44614fe47960f557631775374dc9/sandbox/linux-sandbox/33886/execroot/gapid/external/org_golang_google_grpc/trace.go: import of "golang.org/x/net/trace"
No dependencies were provided.
Check that imports in Go sources match importpath attributes in deps.
[31 / 138] apic generating gapis/api/vulkan/vulkan.api with gapis/api/templates/constant_sets.go.tmpl; 1s linux-sandbox ... (3 actions running)
[32 / 138] apic generating gapis/api/vulkan/vulkan.api with gapis/api/templates/constant_sets.go.tmpl; 3s linux-sandbox ... (2 actions running)
[32 / 138] apic generating gapis/api/vulkan/vulkan.api with gapis/api/templates/constant_sets.go.tmpl; 14s linux-sandbox ... (2 actions running)
Target //:pkg failed to build
INFO: Elapsed time: 20.059s, Critical Path: 15.15s
`
[out.txt](https://github.com/google/agi/files/9135457/out.txt)

**Additional debugging information**
- I'm new to agi and bazel, so easily possible (likely?) there is some issue on my side.
   I did try for a while now to understand/workaround/fix it on my own, but well, no fix so far. Hence any hints are welcome.
- it does build for me on a Ubuntu 20.04 machine (but I need a build running on a machine with an older glibc)
- it did build once (for a bit?). But unknown why it now fails
- I get that this sounds like a setup issue on my side and if not that, then an issue in a dependency and not in agi. Still would be grateful for any insight.
- let me know if there is something I can try out

**Comment by ttanatb** [comment]
Hi, thanks for filing this issue! Assigning to @pmuetschard to help investigate & triage what's causing the issue. The team currently has a bunch of competing priorities, but we'll try to find the time to prioritize this

**Comment by yalcinmelihyasin** [comment]
Can you please share your Go version?

**Comment by ttanatb** [comment]
Closing this issue due to staleness -- feel free to re-open
