### ISSUE TITLE
The server has exited with an error code of: 2 

### ISSUE THREAD

**Issue by Shantanu45** [google/agi#1166]
**Environment information:**
 - AGI version:
 - Host OS: Windows
 If tracing on Android:
 - Device model: Pixel 6
 - Android Version: 12

**Bug description**
Server memory keep increasing to around 40GBs (capture size is 1GB) and finally this Error happens 'panic: runtime error: invalid memory address or nil pointer dereference.'

**Screenshots**
![image](https://user-images.githubusercontent.com/30995267/183412584-bcc5a572-e470-46ca-8fae-ab0af4a5523c.png)

**Log File**
[gapis.log](https://github.com/google/agi/files/9281462/gapis.log)

**Comment by yalcinmelihyasin** [comment]
Hi,

Would it be possible to share more details about this, trace etc.
