### ISSUE TITLE
GPU memory information missing in system profiler

### ISSUE THREAD

**Issue by rmsmelik** [google/agi#1194]
**Environment information:**
 - AGI version: 2022-3.0.1
 - Host OS: Windows
 If tracing on Android:
 - Device model: Samsung Galaxy Tab S7 (tablet)
 - Android Version: 11

**Bug description**
I'm trying to track down a Vulkan GPU shared memory - out of memory error. In the AGI announcement video "Optimize your graphics with Android GPU Inspector frame profiler" it is stated that GPU memory tracking was added to the system profiler traces, however when I run a system profiler trace, the GPU Memory row is missing (I only have Vulkan Events and GPU Counters). Is there some additional configuration needed to get this information?

**Reproduction steps**
Perform a system profiler trace with all options enabled. The information display does not contain the GPU memory category.

**Screenshots**
See the announcement video on youtube: https://youtu.be/lg_kgrCGhYw?t=160

**Comment by ttanatb** [comment]
Could you run `adb shell perfetto --query > perfetto_query.txt` and upload what the results are?

**Comment by rmsmelik** [comment]
Sure! (adb from platform-tools_r33.0.3-windows)
[perfetto_query.txt](https://github.com/google/agi/files/9467595/perfetto_query.txt)

**Comment by ttanatb** [comment]
It looks like this device unfortunately does not support GPU memory profiling (it's missing the `data_source` with a descriptor name `android.gpu.memory`) We're working to have android devices be more consistent in what profiling features it supports with AGI but do not have specific information about `android.gpu.memory`. I'll ask around to try to get a better an answer for why `android.gpu.memory` isn't being reported on the Samsung Galaxy Tab S7

**Comment by ttanatb** [comment]
Sorry, couldn't find helpful answers here -- closing this for now as there isn't anything that can be done from the tool side if the device says it's not capable of providing relevant data.
