### ISSUE TITLE
Can you please explain why do I need this tool if there are standalone Perfetto and Renderdoc

### ISSUE THREAD

**Issue by ruperson** [google/agi#1196]
I recently borrowed a Samsung phone from my friend to see this program and could not think of a use case.
System Profiler as I see is just some calls of perfetto with less flexibility
Frame Profiler seems more interesting, but I couldn't find features which Renderdoc hasn't
Could you please help me to understand the unique key features of this tool because I am definitely wrong somewhere
Thank you in advance

**Comment by kocdemir** [comment]
Hi, 
Thanks for the question. 
AGI provides some debugging functionality but focuses mainly on providing accurate GPU profiling and counter data from the Android devices. Different vendors provide different tools for this purpose, and AGI provides a unified interface to capture, replay and profile vulkan applications. It can use ANGLE to capture GLES applications. RenderDoc, on the other hand, 'is a stand-alone graphics debugging tool' which mainly focuses on the debugging side for the frame capturing. 
Perfetto is the main tool for capturing system traces data on Android platform and we're using it for system profiling and counter data collection. Apart from the UI side changes to provide more GPU and game development oriented focus, one of the main differences here, AGI is setting up the device for GPU counter collection from the target application and enables additional data sources, on top of the existing tracing points collected. This is currently not supported with Perfetto as the process requires providing and enabling vulkan layers on the device, for the target application. It also enables vendors to implement their own data sources for GPU profiling via dynamic libraries. 
Hope this helps, please reopen if you have any additional questions.
