### ISSUE TITLE
zlib missing c function prototypes

### ISSUE THREAD

**Issue by rosasco-wk** [google/agi#1205]
SUMMARY
With fuchsia_clang, I'm getting build errors like this for libgapii target:

Use --sandbox_debug to see verbose messages from the sandbox
external/net_zlib/inflate.c:105:11: error: a function definition without a prototype is deprecated in all versions of C and is not supported in C2x [-Werror,-Wdeprecated-non-prototype]
local int inflateStateCheck(strm)

Per the commit hash, our zlib is from 2017 per:
https://github.com/google/agi/blob/b12d38469611cd97380cae458c4fc3a64e0e0dcc/tools/build/workspace.bzl#L74

commit cacf7f1d4e3d44d871b605da3b647f07d718623f (tag: v1.2.11)
Author: Mark Adler <madler@alumni.caltech.edu>
Date:   Sun Jan 15 09:18:46 2017 -0800

    zlib 1.2.11

Updating zlib may be the remedy.

REPRO
Using source from: https://github.com/rosasco-wk/agi.git  branch: agis_handshake

CC=/usr/bin/gcc-8 bazel build --subcommands --config fuchsia_arm64 //gapii/fuchsia:gapii

**Comment by yalcinmelihyasin** [comment]
Hi,

Are you able to use GCC-9 instead?

We are currently in the process of updating many dependencies and zlib is one of them. In the meanwhile, you may try to use GCC-9 which is used by our CI.

**Comment by rosasco-wk** [comment]
Thanks, yeah, I can use GCC-9.  I do get the same compilation errors though
e.g.:

external/net_zlib/infback.c:28:13: error: a function definition without a
prototype is deprecated in all versions of C and is not supported in C2x
[-Werror,-Wdeprecated-non-prototype]
int ZEXPORT inflateBackInit_(strm, windowBits, window, version, stream_size)

**Comment by rosasco-wk** [comment]
Please note that, although I've changed the command prefix to use GCC-9,
fuchsia_clang is still being used for the Fuchsia target I'm building by
necessity.  Command for the error above is:

CC=/usr/bin/gcc-9 bazel build --subcommands --config fuchsia_arm64
//gapii/fuchsia:gapii

**Comment by rosasco-wk** [comment]
The missing prototypes are still in zlib ala https://github.com/madler/zlib/issues/702.

**Comment by kocdemir** [comment]
Hi, we've made a major update to most of our dependencies, can you please confirm if this issue still affects you with the latest version?

**Comment by rosasco-wk** [comment]
Yes, this is still evident.  Updated build command per AGI changes:  CC=clang-12 bazel build --toolchain_resolution_debug=@bazel_tools//tools/cpp:toolchain_type --subcommands --config fuchsia_arm64 //gapii/fuchsia:gapii


This error can be circumvented by suppressing this warning in .bazelrc.

**Comment by rosasco-wk** [comment]
My branch is based off of:

Author: kocdemir ***@***.***>
Date:   Fri Sep 16 00:05:07 2022 +0100

    handle missing energy tracks case (#1216)

Without adding:

build:fuchsia_arm64 --copt="-Wno-deprecated-non-prototype"
build:fuchsia_arm64 --copt="-Wno-unused-function"

to .bazelrc, I am still getting build errors in my branch.

Examples (amongst dozens, possibly hundreds of instances):

external/com_google_protobuf/src/google/protobuf/generated_message_tctable_lite.cc:347:14:
error: unused function 'Offset' [-Werror,-Wunused-function]
inline void* Offset(void* base, uint32_t offset)

external/net_zlib/adler32.c:63:15: error: a function definition without a
prototype is deprecated in all versions of C and is not supported in C2x
[-Werror,-Wdeprecated-non-prototype]
u

These failures are due to fuchsia_clang being a more modern version of
clang that is more rigorous about enforcing coding standards paired with
older software (e.g. zlib) that no longer complies with modern coding
standards.
