### ISSUE TITLE
Samsung Galaxy S20 FE (SM-G780F) support validation fails

### ISSUE THREAD

**Issue by renaudbedard** [google/agi#1217]
**Environment information:**
 - AGI version: 2022-3.0.1
 - Host OS: Windows
 If tracing on Android:
 - Device model: SM-G780F
 - Android Version: 12

**Bug description**
The documentation states that the Samsung Galaxy S20 series should be supported by AGI, but my device fails support validation.
The error mentions : `Queried result is not 1: {6 GPU active cycles 0x7ff6eedb0f60}`

**Reproduction steps**
- Plug device via USB
- Open the "Capture a new Trace" window in AGI
- Wait for device support validation to run and eventually fail

**Stacktrace**
N/A

**Screenshots**
![image](https://user-images.githubusercontent.com/251134/191643639-7de750a3-2428-4929-a75d-b7d960eeb71b.png)

**Additional debugging information**
[validation910598139.zip](https://github.com/google/agi/files/9621672/validation910598139.zip)
[gapis.log](https://github.com/google/agi/files/9621667/gapis.log)
[logcat-full.txt](https://github.com/google/agi/files/9621691/logcat-full.txt)

**Comment by ttanatb** [comment]
Huh, this is a weird issue likely from the phone itself with the following ominous lines from `logcat-full.txt`
```
09-21 22:21:12.456   988   988 I perfetto: ing_service_impl.cc:912 Configured tracing session 6, #sources:2, duration:7000 ms, #buffers:1, total buffer size:131072 KB, total sessions:1, uid:2000 session name: ""
09-21 22:21:12.469  9649  9652 E mali_gpu_data_source: Failed to initialize HWC reader
09-21 22:21:12.469  9649  9652 E mali_gpu_data_source: Couldn't start because OnSetup failed
```

Is this an issue that occurs consistently? We tend to see errors like this when another activity disrupts the validation process (e.g. switching apps, notifications, etc.)

**Comment by ttanatb** [comment]
Closing this due to the issue being stale -- please re-open if you're still running into this issue. It's possibly a driver bug, but there's not a lot we can do without extra information.
