### ISSUE TITLE
(Version 3.2.1) Explanation of system/per-process power profiling + Suggestion + Issue on Power Usage summary track

### ISSUE THREAD

**Issue by danierspo** [google/agi#1226]
Hello everyone. I'm a student who's studying Android Game Development Kit and the tools it provides to optimize energy consumption. For testing purposes, I'm using Android GPU Inspector's System profiling on a game to get its Battery Usage, Power Rails and Energy Breakdown; but, as far as I can tell (not that much):
1. _Battery Usage_ is referred to the battery used by the **system** (not by the profiled app) in terms of mA (milli-Ampere) in the current poll;
2. _Energy Breakdown_ is also referred to the **system** (not to the profiled app) in terms of "uws" (microwatt per second) for fields CPUCL0, CPUCL1, CPUCL2 and GPU, but I noticed that they have the same values of Power Usage's cpu-little, cpu-mid, cpu-big and gpu, respectively.

Also, for Power Rails, I know that Android GPU Inspector is based on Perfetto for these tracks and that power rails depend on the hardware manufacturer, but I'm also having trouble to figure out what some Power Usage rails refer to, because they have no description (not even in Perfetto docs). Maybe, some of them (like aoc, system-fabric, etc.) should not be considered obvious.

The main problem follows. In the releases page, under 3.2.1 is written: **"Added support and visualization for per-process power profiling. New tracks can now be enabled from the system profile configuration window, under the 'Battery' options."**; then, the following screenshot is attached:
<img width="628" alt="Energy_Breakdown" src="https://user-images.githubusercontent.com/56684426/195314762-c61c69d7-e3fd-4629-8982-50ce6b5d558e.png">

But, when I go in the system profiling configuration window, there's nothing related to a per-process profiling.

After these problems, would it be possible, along with all of these tracks, in a System profiling to tell "During this profiling, the app consumed _x_ mAh", like it's reported in the Battery settings of most phones?

Thank you for your comprehension.

- - - - - - - - - -
**Issue.** In the pull request #1172, a Power Usage summary track was added. I don't have checked if it's a known issue or if this feature has been removed afterwards but, as of now, in the summary graph only the output of the first rail is shown (in my case, tpu), as follows:
![PowerUsageSummaryIssue](https://user-images.githubusercontent.com/56684426/196030624-7a840997-29e8-4bf5-a7da-f9d7542bc61e.png)

**Comment by sonakshisaxena1** [comment]
Hi @danierspo ,
Thanks for your suggestion! Unfortunately, we do not plan to add any new features to AGI for now. We'll definitely keep this in mind if any of the plans change.  

Closing this issue now.
