### ISSUE TITLE
Presubmit isn't faithful between local and infra execution

### ISSUE THREAD

**Issue by rosasco-wk** [google/agi#1228]
This presubmit failure is only evident when run from github:

https://source.cloud.google.com/results/invocations/39836aa1-d635-40fd-9769-5e4a4c118155/targets/agi%2Flinux%2Fpresubmit/log

This build validation failure isn't evident when run locally on Linux so there is a disparity between what is run locally with the kokoro presubmit script and what is being executed by github infra.

**Comment by yalcinmelihyasin** [comment]
Can you please check this again, please let me know if the issue persist.

**Comment by rosasco-wk** [comment]
Note this is for PR: https://github.com/google/agi/pull/1254.  Just tagged w/ a new force-run.

**Comment by yalcinmelihyasin** [comment]
PR has been merged therefore I assume the issue has been resolved.
