### ISSUE TITLE
macOS AGI build broken under XCode 14.1

### ISSUE THREAD

**Issue by rosasco-wk** [google/agi#1240]
### SUMMARY
Build breakage for deprecated function `mktemp()`.

### CONFIGURATION
M1 MBP running XCode 14.1 and macOS 12.6.1

### REPRO STEPS
CC=clang-12 bazel build --subcommands --config fuchsia_x64 //gapii/fuchsia:gapii  

### ERROR
Use --sandbox_debug to see verbose messages from the sandbox and retain the sandbox build root for debugging
core/cc/dl_loader.cpp:52:7: error: 'mktemp' is deprecated: This function is provided for compatibility reasons only.  Due to security concerns inherent in the design of mktemp(3), it is highly recommended that you use mkstemp(3) instead. [-Werror,-Wdeprecated-declarations]
  if (mktemp(tmp) != nullptr) {
      ^
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX13.0.sdk/usr/include/stdlib.h:210:1: note: 'mktemp' has been explicitly marked deprecated here
__deprecated_msg("This function is provided for compatibility reasons only.  Due to security concerns inherent in the design of mktemp(3), it is highly recommended that you use mkstemp(3) instead.")

**Comment by yalcinmelihyasin** [comment]
We are currently using XCode 12.4.

Are there any special requirements for using XCode 14?

**Comment by rosasco-wk** [comment]
Yes,  macOS 13 sdk has changed which results in the reported build failure.

**Comment by yalcinmelihyasin** [comment]
What my question was about, do you have to use XCode 14 or are you able to continue the development with XCode 12.4.

Otherwise, I believe you can install Clang12 separately and set you CC to Clang12 to be able to build it. Is this a reasonable workflow for you?

**Comment by olehkuznetsov** [comment]
Fixed with 3.3.2
