### ISSUE TITLE
Pixel 6 Pro failed validation with FailedTraceValidation Error: Queried result is not 1: {6 GPU active cycles 0x1082d60}

### ISSUE THREAD

**Issue by RenfengLiu** [google/agi#1246]
**Environment information:**
 - AGI version: Android GPU Inspector  Version 2022-3.2.1
 - Host OS:  Linux
 If tracing on Android:
 - Device model: Pixel 6 pro
 - Android Version: 13

![image](https://user-images.githubusercontent.com/1320650/201716122-331495ff-d762-4a05-8523-88ba949b22cd.png)

**Comment by ttanatb** [comment]
Thanks for filing the issue, we were seeing similar failures in https://github.com/google/agi/issues/1234 could you provide the adb logcat and the build number to help with debugging?
- `adb logcat > log.txt`
-  Settings > About phone > scroll to the bottom

**Comment by RenfengLiu** [comment]
see b/259122991

**Comment by ttanatb** [comment]
Closing this, seems to be fixed from the new system update
