### ISSUE TITLE
Device Connection Failed---SamSung S10

### ISSUE THREAD

**Issue by JackKaiXing** [google/agi#1250]
Like someone posted here, https://github.com/google/agi/issues/1131

On my SamSung S10

adb shell "echo 1 > /sys/class/kgsl/kgsl-3d0/perfcounter"
/system/bin/sh: can't create /sys/class/kgsl/kgsl-3d0/perfcounter: Permission denied

**Comment by JackKaiXing** [comment]
Android 12, One UI 4.1. It worked before but now could not be connected.

**Comment by ttanatb** [comment]
What's the build number where you encountered this issue? (Search for build number in `settings`)

**Comment by ttanatb** [comment]
Closing this because it looks like a duplicate of #1252 
If this is not the case, please re-open with more info
