### ISSUE TITLE
com.google.android.gapid.<abi>

### ISSUE THREAD

**Issue by Mamuchehr** [google/agi#1251]
**Environment information:**
 - AGI version:
 - Host OS: [e.g. Linux]
 If tracing on Android:
 - Device model:
 - Android Version:

**Bug description**

**Reproduction steps**

**Stacktrace**
Please paste a stacktrace here if it's available.

**Screenshots**

**Additional debugging information**
- Please attach the generated _gapis.log_ and _gapic.log_ files you will find in the temp folder (e.g. /tmp/ on linux).
- If using Android: Please attach a full logcat dump (```adb logcat -d > logcat-full.txt```) that contains logs since AGI was started.

**Comment by ttanatb** [comment]
It doesn't look like you've provided any details in regards to your bug. It's pretty vague, and I don't know how I can help you.

The bug template is supposed to guide you on what additional info would be helpful for us, so we can best help you.
