### ISSUE TITLE
Fixing a display issue for hw_queues with no data

### ISSUE THREAD

**Issue by dfriederich** [google/agi#1255]
We emit a set containing all the known hardware queues, but usually only some of the queues actually have any data.
agi does not display hw_queues with no data properly, it just allocates a few pixel height for them, not enough
to show the queue name.

packet {
  timestamp_clock_id: 3
  timestamp: 61135264291710
  gpu_render_stage_event {
    duration: 613310
    event_id: 2727
    submission_id: 249
....
    render_pass_handle: 0
    extra_data {
      name: "Queued Jobs"
      value: "0"
    }
    specifications {
      context_spec {
        context: 12970367414202559944
        pid: 18313
      }
      hw_queue {
        name: "Universal IB"
        description: "Universal IB"
      }
      hw_queue {
        name: "Universal"
        description: "Universal"
      }
      hw_queue {
        name: "Compute IB"
        description: "Compute IB"
      }
      hw_queue {
        name: "Compute"
        description: "Compute"
      }
      hw_queue {
        name: "Dma IB"
        description: "Dma IB"
      }
      
      
![image](https://user-images.githubusercontent.com/109323095/209026173-ab0f996c-e6c3-47b5-ad2a-ba856e32b0e0.png)

To fix this I would propose to either use a min height for the row, or even better, not to show it if there is no data.

Trivial patch to show the name, make the height large enough to display the hw queue name:
diff --git a/gapic/src/main/com/google/gapid/perfetto/views/GpuQueuePanel.java b/gapic/src/main/com/google/gapid/perfetto/views/GpuQueuePanel.java
index d8b5754a5..26e07fcf8 100644
--- a/gapic/src/main/com/google/gapid/perfetto/views/GpuQueuePanel.java
+++ b/gapic/src/main/com/google/gapid/perfetto/views/GpuQueuePanel.java
@@ -76,7 +76,7 @@ public class GpuQueuePanel extends TrackPanel<GpuQueuePanel> implements Selectab
 
   @Override
   public double getHeight() {
-    return queue.maxDepth * SLICE_HEIGHT;
+    return Math.max(SLICE_HEIGHT, queue.maxDepth * SLICE_HEIGHT);
   }
 
   @Override

For now showing the row at all if there is no data, (preferred, maybe include both changes?)

index 7a3c70466..46079dff7 100644
--- a/gapic/src/main/com/google/gapid/perfetto/models/Tracks.java
+++ b/gapic/src/main/com/google/gapid/perfetto/models/Tracks.java
@@ -173,6 +173,9 @@ public class Tracks {
         parent = "gpu_queues";
       }
       for (GpuInfo.Queue queue : data.getGpu().queues()) {
+        if (queue.maxDepth == 0) {
+          continue; // Skip queues with no data
+        }
         SliceTrack track = SliceTrack.forGpuQueue(data.qe, queue);
         data.tracks.addTrack(parent, track.getId(), queue.getDisplay(),
             single(state -> new GpuQueuePanel(state, queue, track), true, false));

**Comment by ttanatb** [comment]
I think it's more clear to the user if we include all queues that are available instead of skipping the queue if it is empty (tells the user that this phone _can_ provide info on the queue, but is not in this trace).

Do you have a trace file I can use to test this against? The devices I have access to (with Adreno/Mali GPUs) don't have empty queues.
