### ISSUE TITLE
ValidateGpuSlices doesn't account for events from 'other' PIDs that may not contain a vkCommandBuffer handle

### ISSUE THREAD

**Issue by shaunh-imgtech** [google/agi#1257]
**Environment information:**

 - AGI version: 2022-3.3.0:developer (#1249)
 - Host OS: Ubuntu 20.04
 - Device model: Acer Chromebook R13 64GB (CB5-312T-K1TR)
 - Android Version: 12

**Bug description**

As discussed with Serdar, while implementing the PowerVR device validator I encountered an issue where device validation can fail (in ValidateGpuSlices) due to render stage events triggered by system processes such as surfaceflinger (which still use GLES) being captured & intermixed with render stage events from the Vulkan app (VkSampleActivity) being executed during device validation, which results in only some render stage events containing a valid Vulkan command buffer handle and therefore causing the [check ](https://github.com/google/agi/blob/master/gapis/trace/android/validate/validate.go#L241) in ValidateGpuSlices to fail. In the GUI this manifests with an error message such as: `FailedTraceValidation Error: GPU activity slice Vertex has null command buffer`.

I'm assuming that this issue will only manifest on devices that implement the GPU data producer globally in the form of a "libgpuproducer" library under /vendor (as is the case for PowerVR devices) and not for producers implemented as a Vulkan layer where I'd imagine events are already filtered to include only ones from it's PID.

Serdar mentioned that AGI might be able to filter out render stage events coming from other/non-vk-app PIDs during the validation process.

**Reproduction steps**

- Connect the device and attempt validation.
- On the device I see the spinning textured cube demo (uninterrupted) for a few seconds.
- Validation *may* fail (as noted above this is likely dependent on the implementation of the GPU data producer) with the message above, also see the screenshot below.

I have also attached the Perfetto file that AGI captured during device validation if that helps at all with 'offline' reproduction.

**Screenshots**

![Device validation failure](https://user-images.githubusercontent.com/119497725/209321509-e4b00b88-3432-42d5-a582-54c051e26c93.PNG)

**Additional debugging information**

[gapic.log](https://github.com/google/agi/files/10294349/gapic.log)
[gapis.log](https://github.com/google/agi/files/10294350/gapis.log)
[Perfetto validation file (as quoted in the gapis log)](https://github.com/google/agi/files/10294543/validation2229707191.zip)

**Comment by kocdemir** [comment]
Hi, thanks for the report. We've looked into this but it wasn't that easy to filter out the events based on PIDs, using the existing data in the Perfetto file generated. @ttanatb can provide a better explanation for the limitations and we can check if this is still doable with some other ways.

**Comment by ttanatb** [comment]
From looking at the data reported by perfetto, we only get `pid` values from `Vulkan Events` gpu_slices (not vertex/fragment gpu_slices). Looking through the data, we can choose to validate only gpu_slices with the same `submission_id` as the gpu_slices from the vulkan_event tracks.

Here's what the table looks like
![image](https://user-images.githubusercontent.com/14023901/210408452-dba79560-847d-44ac-9d14-90e37d0c6740.png)
Using the following horrendously formatted SQL query:
```
select gpu_slice.id, gpu_track.name, gpu_track.scope, gpu_slice.context_id, gpu_slice.render_target, gpu_slice.render_pass, gpu_slice.command_buffer, gpu_slice.submission_id, gpu_slice.hw_queue_id
 FROM gpu_slice
 JOIN gpu_track ON gpu_slice.track_id =  gpu_track.id
 ORDER BY gpu_slice.id
```

Here's the visual representation that AGI shows
![image](https://user-images.githubusercontent.com/14023901/210407900-1bd63785-9c57-43f7-b3b9-c9f335dd0841.png)

I think one thing to consider is how this will look like on the frame profiler (AGI runs a perfetto trace against the replay) and it would be useful if AGI indicates which vertex/fragment submissions originated from their app/game. Thoughts?

**Comment by ttanatb** [comment]
https://github.com/google/agi/pull/1262 is up with the fix outlined in the previous [comment](https://github.com/google/agi/issues/1257#issuecomment-1370037070)

**Comment by shaunh-imgtech** [comment]
> Looking through the data, we can choose to validate only gpu_slices with the same submission_id as the gpu_slices from the vulkan_event tracks.

Yes that sounds like it should work to me. One thing to keep in mind though is that submission IDs might not be unique across processes (they are not for PowerVR) so the validator could sporadically fail if we are (very) unlucky and the Vulkan sample app and a non-vulkan process happen to emit the same submission ID during validation.

**Comment by ttanatb** [comment]
>One thing to keep in mind though is that submission IDs might not be unique across processes (they are not for PowerVR) so the validator could sporadically fail if we are (very) unlucky and the Vulkan sample app and a non-vulkan process happen to emit the same submission ID during validation.

Updated #1262 with extra logic to handle this case. Added another map `invalidGpuSlices` to make sure we don't invalidate the result if we run into a valid slice then another slice with the same ID.

**Comment by ttanatb** [comment]
Fixed in https://github.com/google/agi/pull/1262
