### ISSUE TITLE
Presubmit is failing because of Go update

### ISSUE THREAD

**Issue by rosasco-wk** [google/agi#1260]
Presubmit failure on a README.md update:

https://source.cloud.google.com/results/invocations/23ccd744-90ff-4e0f-b8db-27f04ca24d20/targets/agi%2Fpresubmit%2Fpresubmit/log

go: go.mod file not found in current directory or any parent directory.
	'go get' is no longer supported outside a module.
	To build and install a command, use 'go install' with a version,
	like 'go install example.com/cmd@latest'
	For more information, see https://golang.org/doc/go-get-install-deprecation
	or run 'go help get' or 'go help install'.

Evidently operating w/o Go modules will no longer fly so either need to add modules or set some kind of legacy mode flag.

**Comment by rosasco-wk** [comment]
I just checked the `gapic readme` change and the presubmit is still failing but for different reasons on both linux and windows.  Just kicked off another forced run:  https://github.com/google/agi/pull/1254#issuecomment-1375684329

**Comment by yalcinmelihyasin** [comment]
Windows is failing because of outdated GCC which has been fixed on the master branch.

I am closing this as the presubmit now succeeds and build should run fine with the latest master. Please update it again.

**Comment by rosasco-wk** [comment]
Rebased, pushed.  Now retrying...
