### ISSUE TITLE
Encontered an unexpected error when validating with the validator

### ISSUE THREAD

**Issue by Andreyogld3d** [google/agi#1274]
**Environment information:**
 - AGI version: 3.3.0
 - Host OS: Windows 11

**Bug description**
Encontered an unexpected error when validating with the validator

**Reproduction steps**
Try to run agi

![image](https://user-images.githubusercontent.com/8597425/219607449-f9dcac97-6b0e-4ac2-b025-1b7ae393b689.png)

**Additional debugging information**
[gapis.log](https://github.com/google/agi/files/10765275/gapis.log)
[gapic.log](https://github.com/google/agi/files/10765276/gapic.log)

**Comment by ttanatb** [comment]
It looks like you're trying to use AGI against to trace an application running on Windows Desktop. AGI can run on Windows, but we only support tracing of Android devices.

This is unfortunately, not a supported use-case -- feel free to look into Perfetto, RenderDoc, GAPID, or AMD specific tools.
