### ISSUE TITLE
AGI failed validation on S23 Ultra

### ISSUE THREAD

**Issue by FVivolo** [google/agi#1294]
**Environment information:**
 - AGI version: 3.30
 - Host OS: Windows
 If tracing on Android:
 - Device model: SM-918u1
 - Android Version: 13

**Bug description**
Crash better see images

**Reproduction steps**
just try to validate agi app or any app

**Stacktrace**
Please paste a stacktrace here if it's available.

**Screenshots**

**Additional debugging information**
- Please attach the generated _gapis.log_ and _gapic.log_ files you will find in the temp folder (e.g. /tmp/ on linux).
- If using Android: Please attach a full logcat dump (```adb logcat -d > logcat-full.txt```) that contains logs since AGI was started.
![Screenshot 2023-05-01 105228](https://user-images.githubusercontent.com/4428409/235471438-ee584bcd-65d9-4df1-a064-4eb7d43c592f.png)
[gapis.log](https://github.com/google/agi/files/11366007/gapis.log)
[gapic.log](https://github.com/google/agi/files/11366008/gapic.log)

**Comment by idortulov** [comment]
Same thing on Samsung Galaxy S20 FE. Apparently, Samsung is not supported.

**Comment by ttanatb** [comment]
Thank you for reporting this issue! We recently released a new release https://github.com/google/agi-dev-releases/releases/tag/v3.3.1-dev-20230607 please re-open this if you're still running into this problem.
