### ISSUE TITLE
Another crash On S23 Ultra

### ISSUE THREAD

**Issue by FVivolo** [google/agi#1295]
**Environment information:**
 - AGI version: 3.30
 - Host OS: Windows
 If tracing on Android:
 - Device model: SM-918U1
 - Android Version: 13

**Bug description**
Just validate with the app open and get this crash on android

**Reproduction steps**

**Stacktrace**
Please paste a stacktrace here if it's available.

**Screenshots**

**Additional debugging information**
- Please attach the generated _gapis.log_ and _gapic.log_ files you will find in the temp folder (e.g. /tmp/ on linux).
- If using Android: Please attach a full logcat dump (```adb logcat -d > logcat-full.txt```) that contains logs since AGI was started.
![Screenshot 2023-05-01 105737](https://user-images.githubusercontent.com/4428409/235472313-b6f6105e-d1fb-4d77-8b97-ea8f91fa3f1b.png)
![Screenshot_20230501_105552](https://user-images.githubusercontent.com/4428409/235472471-6efab82a-990b-4e81-85dc-ce1406ed3698.png)

[gapic.log](https://github.com/google/agi/files/11366035/gapic.log)
[gapis.log](https://github.com/google/agi/files/11366036/gapis.log)

**Comment by ttanatb** [comment]
This is a dup of https://github.com/google/agi/issues/1294 -- closing this one so we can consolidate the same issue, please follow the thread in the issue linked
