### ISSUE TITLE
EOF error

### ISSUE THREAD

**Issue by zhouhuacong** [google/agi#1297]
**Environment information:**
 - AGI version:
 - Host OS: [e.g. Linux]
 If tracing on Android:
 - Device model:
 - Android Version:

**Bug description**

**Reproduction steps**

**Stacktrace**
Please paste a stacktrace here if it's available.

**Screenshots**

**Additional debugging information**
- Please attach the generated _gapis.log_ and _gapic.log_ files you will find in the temp folder (e.g. /tmp/ on linux).
- If using Android: Please attach a full logcat dump (```adb logcat -d > logcat-full.txt```) that contains logs since AGI was started.

**Comment by ttanatb** [comment]
Thanks for filing this issue, but there's not enough information in here for us to triage. Please provide description, repro steps, screenshots, or logs
