### ISSUE TITLE
Pixel 5 stucks on Initializing

### ISSUE THREAD

**Issue by morder** [google/agi#1298]
**Environment information:**
 - AGI version: 3.3.0
 - Host OS: Linux EndeavourOS 6.3.1-arch1-1
 If tracing on Android:
 - Device model: Pixel 5
 - Android Version: 13

**Bug description**
Capturing stuck on `Initializing` 

**Reproduction steps**
Every time a got this situation

**Screenshots**
![image](https://user-images.githubusercontent.com/1358094/236471642-8db812a3-abca-43b8-8e50-74d078bcec15.png)
![image](https://user-images.githubusercontent.com/1358094/236471719-73894b4a-391c-45c1-a325-f765fd9d09bd.png)

**Additional debugging information**
- I can't find any _gapis.log_ and _gapic.log_ files 
- logs: https://gist.github.com/morder/130cc4cd11e5bde8dc358014e6db1535

**Comment by ttanatb** [comment]
This is an issue we've seen from time to time, depending on the package (game) -- if this game spawns multiple processes then try providing the name of the process you want to listen to in the `Process Name` field.
