### ISSUE TITLE
Failed to validate the trace of the sample application with android validaor in S21 device

### ISSUE THREAD

**Issue by Ghost-yc** [google/agi#1301]
**Environment information:**
 - AGI version:2023-3.3.0
 - Host OS: Windows
 If tracing on Android:
 - Device model:Galaxy S21 FE 5G SM-G9900
 - Android Version: Android 13

**Bug description**
FailedTraceValidation Error: Passed 2 checks out of 9, expected to pass 9 check(s). Failed check for 7 counter(s): [{1 Clocks / Second 0x7ff6b0ba1880} {3 GPU %!U(MISSING)tilization 0x7ff6b0ba1880} {21 %!S(MISSING)haders Busy 0x7ff6b0ba1880} {26 Fragment ALU Instructions / Sec (Full) 0x7ff6b0ba1880} {31 Textures / Fragment 0x7ff6b0ba1880} {37 %!T(MISSING)ime Shading Fragments 0x7ff6b0ba1880} {38 %!T(MISSING)ime Shading Vertices 0x7ff6b0ba1880}]

**Reproduction steps**
Plug in  phone to run the verification process

**Stacktrace**

**Screenshots**
![image](https://github.com/google/agi/assets/8528210/0abde9b1-1a91-4c95-8b6f-a442ac69f860)

**Additional debugging information**
[gapis.log](https://github.com/google/agi/files/11574206/gapis.log)

**Comment by ninh-huynh** [comment]
Any solution to fix this? I met the same problem.

**Comment by kocdemir** [comment]
Hi, can you try the latest version(3.3.1) of the tool and let us know if that fixes the issue? 

Thanks

**Comment by ninh-huynh** [comment]
Yeah, I already use the latest version from GitHub release. 
<img width="676" alt="image" src="https://github.com/google/agi/assets/28674990/fdcaef45-8369-4300-99f7-3e939e3fb53b">

**Comment by Cliwo** [comment]
Same here. with the samsung SM-G986N (S20+).
Is there any fix?

**Comment by sDeemm** [comment]
Same here, on SM-G781W. I suspect a permission issue to sample the GPU counters
