### ISSUE TITLE
AGI failed validation on Oppo PEEM00 

### ISSUE THREAD

**Issue by uncleheng** [google/agi#1303]
Environment information:

AGI version: 3.30
Host OS: Mac
If tracing on Android:
Device model: OPPO PEEM00
Android Version: 13
Bug description
Crash better see images

Reproduction steps
just try to validate agi app or any app

Stacktrace
Please paste a stacktrace here if it's available.

Screenshots

Additional debugging information

Please attach the generated gapis.log and gapic.log files you will find in the temp folder (e.g. /tmp/ on linux).
If using Android: Please attach a full logcat dump (adb logcat -d > logcat-full.txt) that contains logs since AGI was started.
![image](https://github.com/google/agi/assets/120434995/9e05867b-d249-4b03-b0da-d221f33beb6c)
[gapic.log](https://github.com/google/agi/files/11673505/gapic.log)
[gapis.log](https://github.com/google/agi/files/11673506/gapis.log)

**Comment by ttanatb** [comment]
Thank you for reporting this issue! We recently released a new release https://github.com/google/agi-dev-releases/releases/tag/v3.3.1-dev-20230607 please re-open this if you're still running into this problem.
