### ISSUE TITLE
Samsung SM-F721B - Android 13 API 33 Validation Failure

### ISSUE THREAD

**Issue by joulei** [google/agi#1308]
**Environment information:**
 - AGI version: 3.3.0
 - Host OS: MacOS Venutra (M2)
 If tracing on Android:
 - Device model: Samsung SM-F721B
 - Android Version: 13 API 33

**Bug description**
Validation failure

**Reproduction steps**
Create a new trace

**Stacktrace**
```
FailedTraceValidation Error: Passed 2 checks out of 9, expected to pass 9 check(s). Failed check for 7 counter(s): [{1 Clocks / Second 0x4742c20} {3 GPU %!U(MISSING)tilization 0x4742c20} {21 %!S(MISSING)haders Busy 0x4742c20} {26 Fragment ALU Instructions / Sec (Full) 0x4742c20} {31 Textures / Fragment 0x4742c20} {37 %!T(MISSING)ime Shading Fragments 0x4742c20} {38 %!T(MISSING)ime Shading Vertices 0x4742c20}]
```

**Screenshots**
![image](https://github.com/google/agi/assets/22042418/65e9136d-0c7d-41e4-af0e-bc1b6cac55ce)

**Additional debugging information**
- Please attach the generated _gapis.log_ and _gapic.log_ files you will find in the temp folder (e.g. /tmp/ on linux).
- Server log [gapis.log](https://github.com/google/agi/files/11907576/gapis.log)
- Client log [gapic.log](https://github.com/google/agi/files/11907582/gapic.log)
- adb logcat -d > logcat-full.txt [logcat-full.txt](https://drive.google.com/file/d/1_IMQwDFbFX0_b1G0Pe1WDJRevswNtg57/view?usp=sharing)

**Comment by olehkuznetsov** [comment]
Should be fixed in 3.3.2
