### ISSUE TITLE
Cannot run Android GPU Inspector over Nexus 5X API 31

### ISSUE THREAD

**Issue by InigoLiceranzu** [google/agi#1312]
**Environment information:**
 - AGI version:
 - Host OS: [e.g. Linux]
 If tracing on Android:
 - Device model:
 - Android Version:

**Bug description**

**Reproduction steps**

**Stacktrace**
Please paste a stacktrace here if it's available.

**Screenshots**

**Additional debugging information**
- Please attach the generated _gapis.log_ and _gapic.log_ files you will find in the temp folder (e.g. /tmp/ on linux).
- If using Android: Please attach a full logcat dump (```adb logcat -d > logcat-full.txt```) that contains logs since AGI was started.

**Comment by olehkuznetsov** [comment]
Should be fixed in 3.3.2
