### ISSUE TITLE
Nothing phone (1) fails validation

### ISSUE THREAD

**Issue by SamCZ** [google/agi#1320]
**Environment information:**
 - AGI version: 3.3.0
 - Host OS: Arm MacOS
 - Device model: Nothing phone (1)
 - Android Version: 13

**Bug description**
Does not validate the GPU

**Reproduction steps**
1. Run the app on phone
2. Run AGI
3. Try to connect with AGI

**Stacktrace**
`FailedPrecondition Error: GPU profiling support not detected on device (9a0a1f8f165b4d967f6a506732943d000e1ae6c2)`

**Screenshots**
<img width="682" alt="image" src="https://github.com/google/agi/assets/5303066/11505fa4-4c43-40c9-bb23-c847be2dbd03">

**Additional debugging information**
Could not find a gapis log on macos
[logcat-full.txt](https://github.com/google/agi/files/12696480/logcat-full.txt)

**Comment by olehkuznetsov** [comment]
Should be fixed in 3.3.2
