### ISSUE TITLE
The application I want to capture is not in the list

### ISSUE THREAD

**Issue by ruiwng** [google/agi#1321]
**Environment information:**
 - AGI version: 3.3.1
 - Host OS:MacOS
 If tracing on Android:
 - Device model: Google Pixel 4a
 - Android Version:  Android 11 API 30

**Bug description**
I have installed an app in the phone, but I cannot find it in the application list.

**Reproduction steps**

**Stacktrace**
no stacktrace.

**Screenshots**
![bCkQhehWcV](https://github.com/google/agi/assets/10192495/317d5be1-3e10-49a8-b5de-29770ccc9f94)

**Additional debugging information**
- Please attach the generated _gapis.log_ and _gapic.log_ files you will find in the temp folder (e.g. /tmp/ on linux).
- If using Android: Please attach a full logcat dump (```adb logcat -d > logcat-full.txt```) that contains logs since AGI was started.

**Comment by olehkuznetsov** [comment]
Application should be debuggable
