### ISSUE TITLE
AGI doesnt support OnePlus 2 Nord 5G

### ISSUE THREAD

**Issue by o-leleka-hitzone** [google/agi#1323]
**Environment information:**
 - AGI version: 3.3.0
 - Host OS: Windows 11
 If tracing on Android:
 - Device model: OnePlus 2 Nord 5G (DN2103)
 - Android Version: 11 API 30

**Bug description**
AGI reports device is not supported. Please add support for this device.

**Comment by o-leleka-hitzone** [comment]
FailedPrecondition Error: GPU profiling support not detected on device

**Comment by olehkuznetsov** [comment]
Should be fixed in 3.3.2
