### ISSUE TITLE
No device connected that supports this trace type.

### ISSUE THREAD

**Issue by t2prince** [google/agi#1325]
**Environment information:**
 - AGI version: 3.3
 - Host OS : Mac OS Ventura 13.4
 - Device model: Samsung Galaxy 21 Ultra (SM-G998N)
 - Android Version: 13

**Bug description**
- No device connected that supports this trace type.

**Reproduction steps**
- Open AGI
- Connect by USB
- Push Reload Button
- Then, No interaction. 

**Screenshots**
![스크린샷 2023-10-16 오후 6 02 30](https://github.com/google/agi/assets/58452733/40a928e2-cade-4288-8ad4-4f7f3d442847)

**More**
- I can use adb by terminal
- Not open Android Studio
- On Android Studio, I can debug the phone.

**Comment by olehkuznetsov** [comment]
Should be fixed in 3.3.2
