### ISSUE TITLE
'NXArchInfo' is deprecated: first deprecated in macOS 13.0. 

### ISSUE THREAD

**Issue by t2prince** [google/agi#1326]
**Environment information:**
 - AGI version: 3.3.1
 - Host OS: macOS 13.4.1

**Bug description**
bazel-out/darwin_arm64-fastbuild/bin/external/breakpad/_virtual_includes/breakpad/common/mac/arch_utilities.h:41:7: error: 'NXArchInfo' is deprecated: first deprecated in macOS 13.0 - No longer supported [-Werror,-Wdeprecated-declarations]
const NXArchInfo* BreakpadGetArchInfoFromName(const char* arch_name);

**Reproduction steps**
1. bazel build pkg

**Screenshots**
<img width="565" alt="스크린샷 2023-10-17 오후 8 17 17" src="https://github.com/google/agi/assets/58452733/88af9ee9-9a2a-4ec2-8cba-d0d9295d6635">

**Additional debugging information**
'NXArchInfo' is deprecated: first deprecated in macOS 13.0.

**Comment by olehkuznetsov** [comment]
Fixed in 3.3.2
