### ISSUE TITLE
Failed Validation on Galaxy S22

### ISSUE THREAD

**Issue by redglasses67** [google/agi#1330]
**Environment information:**
 - AGI version: 2023-3.3.0
 - Host OS: Windows 10
 If tracing on Android:
 - Device model: samsung SC-51C Galaxy S22
 - Android Version: 13

**Bug description**
Failed Validation on Galaxy S22

**Reproduction steps**
  Open AGI.
  Chose 'Capture a new trace'.
  Chose 'Frame Profile - Vulkan'.

**Stacktrace**
Please paste a stacktrace here if it's available.
FailedTraceValidation Error: Passed 2 checks out of 9, expected to pass 9 check(s). Failed check for 7 counter(s): [{1 Clocks / Second 0x7ff6cbc31880} {3 GPU %!U(MISSING)tilization 0x7ff6cbc31880} {21 %!S(MISSING)haders Busy 0x7ff6cbc31880} {26 Fragment ALU Instructions / Sec (Full) 0x7ff6cbc31880} {31 Textures / Fragment 0x7ff6cbc31880} {37 %!T(MISSING)ime Shading Fragments 0x7ff6cbc31880} {38 %!T(MISSING)ime Shading Vertices 0x7ff6cbc31880}]

**Screenshots**

![image](https://github.com/google/agi/assets/15045807/0fac4378-3e7f-4261-afa7-8d910eca8a55)

**Additional debugging information**
- Please attach the generated _gapis.log_ and _gapic.log_ files you will find in the temp folder (e.g. /tmp/ on linux).
- If using Android: Please attach a full logcat dump (```adb logcat -d > logcat-full.txt```) that contains logs since AGI was started.

**Comment by mossmana** [comment]
I encounter this issue for both `Frame Profile - Vulkan` and `Frame Profile - OpenGL on ANGLE` on my Samsung S23 Ultra.

I noticed on https://developer.android.com/agi/supported-devices, that only up to Samsung S21 is documented as supported.

So, failed validation is likely expected in this case.

**Comment by olehkuznetsov** [comment]
Should be fixed in 3.3.2
