### ISSUE TITLE
Mali GPU Performance Counter Monitoring

### ISSUE THREAD

**Issue by hosunhc** [google/agi#1338]
Hi, I was just wondering what setups are required to be able to monitor the GPU counters for Mali devices. 
Using the AGI tool, I'm able to easily gather performance counters, but if i take the configuration file and try to monitor counters using Perfetto, I am unable to do so. 
The perfetto discord group indicated to check these lines of codes and add them to my script: https://github.com/google/agi/blob/95af8ad4c093465c0f1e74fa05c9cc3802594fa9/core/os/android/adb/commands.go#L561
I used the command `adb shell setprop gpuDebugProperty 1`
However, I wasn't able to get the result that I wanted. Are there any other requirements that are needed before I choose to monitor performance counters?
Or am i setting the system properties incorrectly
Thanks!

**Comment by olehkuznetsov** [comment]
One specificity of GPU profiling is that some of the perfetto data producers are inside GPU drivers, and they need to be started before a trace with these GPU data sources can be taken. To start these GPU-specific perfetto data producers, AGI has a small agi_launch_producer utility (see source in cmd/launch_producer/). On Android, AGI extracts this utiliy from its own APK and invokes it, such that the relevant GPU data producers are started (see gapidapk/gapidapk.go:EnsurePerfettoProducerLaunched()).
