### ISSUE TITLE
AGI does not support Rog phone 3

### ISSUE THREAD

**Issue by elmajime** [google/agi#1343]
**Environment information:**
 - AGI version: Version 2023-3.3.0
 - Host OS: Windows
 If tracing on Android:
 - Device model: Rog phone 3
 - Android Version: Android 12

**Bug description**
FailedPrecondition Error: GPU profiling support not detected on device (200852f1a2fa415ca76a972d3d18cad25fd29a58)

This is quiet important for me since I'm using these phones to teach AR mobile development.

**Reproduction steps**
Using a Rog phone 3, the precondition fail.

**Additional debugging information**
[gapis.log](https://github.com/google/agi/files/15050982/gapis.log)

**Comment by olehkuznetsov** [comment]
Should be fixed in 3.3.2
