### ISSUE TITLE
[Issue] Supported GPU but device not supported

### ISSUE THREAD

**Issue by ahmednobii** [google/agi#1348]
**Environment information:**
 - AGI version:  2023-3.3.0:55d96149deb160d0214d73d0e70cb5c799d97416
 - Host OS: [macOS 14.5]
 If tracing on Android:
 - Device model: Xiaome Poco X3 Pro
 - Android Version: 12 API level 31

**Bug description**
it always appears is failed even my the GPU is Qualcomm® Adreno™ 640 which supposed is supported according to devices list. I know u support the listed devices, but i am looking for to use it
Error state
FailedPrecondition Error: GPU profiling support not detected on device (e5b3e16a7b9a181e38cec9ccffac65db343fa142)

**Comment by dvdface** [comment]
Your device is not in supported devices list.

**Comment by olehkuznetsov** [comment]
Should be fixed in 3.3.2
