### ISSUE TITLE
Failed to validate gpu profiling

### ISSUE THREAD

**Issue by prayshouse** [google/agi#1379]
**Environment information:**
 - AGI version: 3.3.0
 - Host OS: Windows 10
 If tracing on Android:
 - Device model: OnePlus Ace 2 Pro
 - Android Version: 14

**Bug description**
OnePlus Ace 2 Pro not support agi

**Reproduction steps**
gapit.exe validate_gpu_progiling

**Stacktrace**
17:15:06.564 I: <gapit> Exec: D:\AndroidGPUInspector\AGI\gapis.exe --enable-local-files --idle-timeout 1m --log-level Info --log-style brief --gapis-auth-token WRka8fF2
17:15:07.715 I: <gapis.exe> 17:15:07.713 W: <gapis> FUCHSIA_FFX_PATH is not set, disabling Fuchsia device monitoring.
17:15:08.489 I: <gapis.exe> 17:15:08.489 I: <gapis> Adding new device
17:15:08.489 I: <gapis.exe> 17:15:08.489 I: <gapis> New scheduler for device: 47692f123411785810357345bcbc89853841de88
17:15:08.489 I: <gapis.exe> 17:15:08.489 I: <gapis> New trace scheduler for device: 47692f123411785810357345bcbc89853841de88 HIH-D-29026
17:15:08.537 I: <gapis.exe>
17:15:08.537 I: <gapis.exe> Bound on port '64693'
17:15:08.537 I: <gapis.exe> 17:15:08.537 I: <gapis> Starting grpc server
17:15:09.436 I: [Try ABI: arm64-v8a⇒gapidapk.EnsureInstalled] <gapis> Examining gapid.apk on host...
17:15:09.518 I: [Try ABI: arm64-v8a⇒gapidapk.EnsureInstalled] <gapis> Looking for gapid.apk...
17:15:09.768 I: [Try ABI: arm64-v8a⇒gapidapk.EnsureInstalled] <gapis> Found gapid package...
17:15:10.128 W: <gapis> Failed to query developer driver: Process returned error
   Cause: exit status 1, assuming no developer driver found.
17:15:10.218 I: <gapis> No developer driver found, attempting to use GPU profiling libraries in system image.
17:15:11.274 W: <gapis> Failed to query developer driver: Process returned error
   Cause: exit status 1, assuming no developer driver found.
17:15:11.787 I: <gapis> [launch producer] I: Trying libgpudataproducer.so
17:15:11.787 I: <gapis> [launch producer] I: Calling start at 0x7aa3339db0
17:15:11.792 I: <gapis> [launch producer] [926.020] perfetto.cc:37699       Producer connected
17:15:11.840 I: <gapis> [launch producer] rm: /data/data/agi_launch_producer/*.SDP.*: No such file or directory
17:15:11.882 I: <gapis> [launch producer] [926.111] ersDataProducer.cpp:790 Unrecognized GPU: A740. Setting the max GPU frequency to int::max.
17:15:11.884 I: <gapis> [launch producer] [926.112] ersDataProducer.cpp:241 gpu.counters: Starting tracing thread
17:15:11.887 I: <gapis> [launch producer] [926.115] perfetto.cc:37699       Producer connected
17:15:12.095 I: <gapis> [launch producer] [926.323] ersDataProducer.cpp:317 Start counter trace returned 0
17:15:12.798 I: [startDevInfoService] <gapis> Attempt to start service: com.google.android.gapid.DeviceInfoService
17:15:18.744 E: <gapis> Unable to enable Adreno GPU counters: Unable to write to sysfs node: <nil>
17:15:18.744 I: <gapis> Adding new device
17:15:18.744 I: <gapis> Adding new device
17:15:18.744 I: <gapis> New scheduler for device: e45c4a507ee8c3c942443f0aaa16993eaeed3ca3
17:15:18.744 I: <gapis> New trace scheduler for device: e45c4a507ee8c3c942443f0aaa16993eaeed3ca3 OnePlus PJA110
-- Device 0: 47692f123411785810357345bcbc89853841de88 --
17:15:18.800 I: [ValidateDevice] <gapis> Device validation failed with error code (0) and reason:
Device is validated.
-- Device 1: e45c4a507ee8c3c942443f0aaa16993eaeed3ca3 --
17:15:18.806 I: [ValidateDevice] <gapis> Validating device (Adreno (TM) 740) with (ADRENO) validator
17:15:19.905 W: [start⇒ValidateDevice] <gapis> Failed to query developer driver: Process returned error
   Cause: exit status 1, assuming no developer driver found.
17:15:19.996 I: [start⇒ValidateDevice] <gapis> No developer driver found, attempting to use GPU profiling libraries in system image.
17:15:20.692 I: [start⇒ValidateDevice] <gapis> Unlocking device screen
17:15:21.598 I: <gapis> [launch producer] Exit.
17:15:21.598 E: <gapis> [EnsurePerfettoProducerLaunched] error: exit status 143
17:15:21.764 W: [start⇒ValidateDevice] <gapis> Failed to query developer driver: Process returned error
   Cause: exit status 1, assuming no developer driver found.
17:15:22.123 I: [start⇒ValidateDevice] <gapis> [launch producer] I: Trying libgpudataproducer.so
17:15:22.123 I: [start⇒ValidateDevice] <gapis> [launch producer] I: Calling start at 0x7483179db0
17:15:22.128 I: [start⇒ValidateDevice] <gapis> [launch producer] [936.356] perfetto.cc:37699       Producer connected
17:15:22.144 I: [start⇒ValidateDevice] <gapis> [launch producer] rm: /data/data/agi_launch_producer/*.SDP.*: No such file or directory
17:15:22.209 I: [start⇒ValidateDevice] <gapis> [launch producer] [936.439] ersDataProducer.cpp:790 Unrecognized GPU: A740. Setting the max GPU frequency to int::max.
17:15:22.213 I: [start⇒ValidateDevice] <gapis> [launch producer] [936.441] ersDataProducer.cpp:241 gpu.counters: Starting tracing thread
17:15:22.213 I: [start⇒ValidateDevice] <gapis> [launch producer] [936.442] perfetto.cc:37699       Producer connected
17:15:22.411 I: [start⇒ValidateDevice] <gapis> [launch producer] [936.640] ersDataProducer.cpp:317 Start counter trace returned 0
17:15:25.601 I: [start⇒ValidateDevice] <gapis> [launch producer] [939.826] perfetto.cc:38150       Setting up data source 20 gpu.counters
17:15:25.601 I: [start⇒ValidateDevice] <gapis> [launch producer] [939.826] perfetto.cc:38150       Setting up data source 19 gpu.renderstages
17:15:25.601 I: [start⇒ValidateDevice] <gapis> [launch producer] [939.827] perfetto.cc:38224       Starting data source 19
17:15:25.601 I: [start⇒ValidateDevice] <gapis> [launch producer] [939.827] ersDataProducer.cpp:373 gpu.counters: OnSetup called, name: gpu.counters, trace_duration_ms: 7000, counter_period_ms: 50, tracing_session_id: 4, session: 0xb400007482aa2dc0
17:15:25.601 I: [start⇒ValidateDevice] <gapis> [launch producer] [939.828] perfetto.cc:38224       Starting data source 20
17:15:25.601 I: [start⇒ValidateDevice] <gapis> [launch producer] [939.828] ersDataProducer.cpp:397 gpu.counters: OnStart called, session: 0xb400007482aa2dc0
17:15:37.605 I: [start⇒ValidateDevice] <gapis> [launch producer] [951.832] perfetto.cc:38245       Stopping data source 19
17:15:37.606 I: [start⇒ValidateDevice] <gapis> [launch producer] [951.833] perfetto.cc:38245       Stopping data source 20
17:15:38.618 I: [start⇒ValidateDevice] <gapis> [launch producer] [952.846] perfetto.cc:38283       Ending async stop of data source 19
17:15:39.623 I: [start⇒ValidateDevice] <gapis> [launch producer] [953.850] ersDataProducer.cpp:413 gpu.counters: OnStop called, session: 0xb400007482aa2dc0
17:15:39.625 I: [start⇒ValidateDevice] <gapis> [launch producer] [953.853] perfetto.cc:38283       Ending async stop of data source 20
17:15:42.685 I: [ValidateDevice] <gapis> Perfetto trace size 61284 bytes
17:15:42.713 I: [ValidateDevice] <gapis> Writing trace size 61284 bytes to C:\Users\ZHOUSI~1\AppData\Local\Temp\validation760077336.perfetto
Device validation failed: Passed 4 checks out of 9, expected to pass 9 check(s). Failed check for 5 counter(s): [{21 %!S(MISSING)haders Busy 0x7ff71f2d1880} {26 Fragment ALU Instructions / Sec (Full) 0x7ff71f2d1880} {31 Textures / Fragment 0x7ff71f2d1880} {37 %!T(MISSING)ime Shading Fragments 0x7ff71f2d1880} {38 %!T(MISSING)ime Shading Vertices 0x7ff71f2d1880}], trace file: C:\Users\ZHOUSI~1\AppData\Local\Temp\validation760077336.perfetto
17:15:43.454 I: [ValidateDevice] <gapis> Device validation failed with error code (3) and reason: Passed 4 checks out of 9, expected to pass 9 check(s). Failed check for 5 counter(s): [{21 %!S(MISSING)haders Busy 0x7ff71f2d1880} {26 Fragment ALU Instructions / Sec (Full) 0x7ff71f2d1880} {31 Textures / Fragment 0x7ff71f2d1880} {37 %!T(MISSING)ime Shading Fragments 0x7ff71f2d1880} {38 %!T(MISSING)ime Shading Vertices 0x7ff71f2d1880}]
17:15:43.454 W: [start⇒ValidateDevice] <gapis> Killing C:\Users\zhousihao\AppData\Local\Android\Sdk\platform-tools\adb.exe (context cancelled)
17:15:43.454 I: [start⇒ValidateDevice] <gapis> [launch producer] Exit.
17:15:43.454 E: [start⇒ValidateDevice] <gapis> [EnsurePerfettoProducerLaunched] error: context canceled
17:15:43.455 E: <gapit> Main failed
Error: Some device failed validation

**Screenshots**

**Additional debugging information**
- Please attach the generated _gapis.log_ and _gapic.log_ files you will find in the temp folder (e.g. /tmp/ on linux).
- If using Android: Please attach a full logcat dump (```adb logcat -d > logcat-full.txt```) that contains logs since AGI was started.
[gapic.log](https://github.com/user-attachments/files/17393136/gapic.log)
[gapis.log](https://github.com/user-attachments/files/17393135/gapis.log)

**Comment by olehkuznetsov** [comment]
Should be fixed in 3.3.2
