### ISSUE TITLE
Redmi Xiaomi 11 lite 5g fails validation

### ISSUE THREAD

**Issue by rafal1137** [google/agi#1385]
**Environment information:**
 - AGI version:  2023-3.3.0:55d96149deb160d0214d73d0e70cb5c799d97416
 - Host OS: Windows 10 Pro
 If tracing on Android:
 - Device model: Redmi Xiaomi 11 lite 5g
 - Android Version: 13

**Bug description**
When you try to trace a new frame it does not pass validation

**Reproduction steps**
1. Open AGI
2. Accept Installing apk on your smartphone (if not installed yet)
3. Click on File
4. Click on Capture Trace

**Stacktrace**
Not available

**Screenshots**
![Image](https://github.com/user-attachments/assets/8c6c380b-205c-4898-ad9b-e4de71023d4b)

**Additional debugging information**
Logcat Dump:
[logcat-full.txt](https://github.com/user-attachments/files/17846826/logcat-full.txt)

**Comment by olehkuznetsov** [comment]
Should be fixed in 3.3.2
