### ISSUE TITLE
AGI needs to add the duration (in ms) to the hovertip

### ISSUE THREAD

**Issue by alecazam** [google/agi#1389]
**Environment information:**
 - AGI version: 2023-3.3.0:55d96149deb160d0214d73d0e70cb5c799d97416
 - Host OS: macOS
 If tracing on Android:
 - Device model: Samsung Galaxy S10e
 - Android Version: 12

**Bug description**
This is a feature request for adding the timing to each hovertip.  Making users select a flamegraph to see a timing is slow, and prevents comparisons with selected timestamps.  I should be able to hover over any and see the duration.  Perfetto finally added this as well, but it's a requirement for any flamegraph.

**Reproduction steps**
Just hover over a timing in the System Profile

**Stacktrace**
N/A

**Screenshots**
Here the hovertip shows the name, but I can already read that.  So the hovertip is only useful on small scopes where the name is not readable.  But it's the duration that is also needed.
<img width="251" alt="Image" src="https://github.com/user-attachments/assets/edcaa2a1-c091-441b-a880-214ba48b45bd" />

**Additional debugging information**
N/A

**Comment by olehkuznetsov** [comment]
Done with: https://github.com/google/agi/pull/1397
