### ISSUE TITLE
samsung SM-S911N - Android 14 API 34 - Qualcomm Adreno (TM) 740 - R3CWC0GB7ZX

### ISSUE THREAD

**Issue by codevania** [google/agi#1400]
**Environment information:**
 - AGI version:
 - Host OS: [e.g. Linux]
 If tracing on Android:
 - Device model:
 - Android Version:

**Bug description**

**Reproduction steps**

**Stacktrace**
Please paste a stacktrace here if it's available.

**Screenshots**
![Image](https://github.com/user-attachments/assets/682ed24b-80ca-488c-a113-a665011ae2b1)

**Additional debugging information**
- Please attach the generated _gapis.log_ and _gapic.log_ files you will find in the temp folder (e.g. /tmp/ on linux).
- If using Android: Please attach a full logcat dump (```adb logcat -d > logcat-full.txt```) that contains logs since AGI was started.

**Comment by olehkuznetsov** [comment]
Can you check in newer version, please?

[v3.3.3 dev](https://github.com/google/agi-dev-releases/releases/tag/v3.3.3-dev-20241220)
