### ISSUE TITLE
Replay may be incorrect if a Vulkan fence was waited on with a non-inf timeout. 

### ISSUE THREAD

**Issue by AWoloszyn** [google/agi#27]
AGI replay will re-run the VkWaitForFences as observed during the trace.
This may be incorrect if WAIT_ALL was set and/or if the timeout was non infinite.

Replay should at least wait for at least the same set of synchronization primitives as this call returned.

**Comment by pau-baiget** [comment]
@johnplate could you please take a look at this one, please?

**Comment by johnplate** [comment]
@AWoloszyn Did you mean "if WAIT_ALL was _not_ set"?
And there is no "infinite" defined for this function. Do we want to define a threshold for an "infinite" duration?

**Comment by AWoloszyn** [comment]
Sorry, to be more clear.
If the timeout is not SUFFICIENTLY LONG* (where sufficiently long is defined as: both the trace and replay NEVER hit the timeout)

And if WAIT_ALL is NOT set. If wait_all is not set, then the returns may not be the same in replay.

**Comment by AWoloszyn** [comment]
I do also consider UINT64_MAX nanoseconds to be sufficiently close to infinity that we typically treat it as such. Unlikely someone will be running for 500+ yrs

**Comment by yalcinmelihyasin** [comment]
Do we get any information, if the fence wait stopped because of a signaling e.g vkQueueSubmit or timeout? 

Why don't we wait as duration of timeout variable?

**Comment by pau-baiget** [comment]
Lowering priority since it's not a blocker but still keeping it to P2 since we need to revisit this in the future.

**Comment by AWoloszyn** [comment]
I would be worried about dropping the priority, 
VkWaitForFences(VkDevice, VkFence, 42)
will simply not replay correctly (reliably)

**Comment by yalcinmelihyasin** [comment]
This has been fixed with #430
