### ISSUE TITLE
delve debug: could not launch process: decoding dwarf section info at offset 0x0: too short

### ISSUE THREAD

**Issue by official-minister** [google/agi#274]
windows 10 
bazel : 2.0.0
delve version: 1.4
compile step:
1. bazel --host_jvm_args=-Djavax.net.ssl.trustStore="D:\JDK\jre\lib\security\cacerts"  build pkg
2. cd D:\GoogleAGI\agi-master\
3. mkdir agi-gofuse
4. bazel --host_jvm_args=-Djavax.net.ssl.trustStore="D:\JDK\jre\lib\security\cacerts" run //cmd/gofuse -- -dir D:\GoogleAGI\agi-master\agi-gofuse --bazelout="D:\GoogleAGI\agi-master\agi-master\bazel-out"
(https://user-images.githubusercontent.com/22905006/81367757-a4516480-9120-11ea-9509-465eb094a645.png),like this:
C:\Users\wyvm3kp4\external\org_golang_x_tools\go\ssa\ssautil\load_test.go -> D:\GoogleAGI\agi-master\agi-gofuse\src\golang.org\x\tools\go\ssa\ssautil\load_test.go
--- Symlinking source file:
 C:\Users\wyvm3kp4\external\org_golang_x_tools\go\ssa\ssautil\switch.go -> D:\GoogleAGI\agi-master\agi-gofuse\src\golang.org\x\tools\go\ssa\ssautil\switch.go
--- Symlinking source file:
 C:\Users\wyvm3kp4\external\org_golang_x_tools\go\ssa\ssautil\switch_test.go -> D:\GoogleAGI\agi-master\agi-gofuse\src\golang.org\x\tools\go\ssa\ssautil\switch_test.go
--- Symlinking source file:
 C:\Users\wyvm3kp4\external\org_golang_x_tools\go\ssa\ssautil\testdata\switches.go -> D:\GoogleAGI\agi-master\agi-gofuse\src\golang.org\x\tools\go\ssa\ssautil\testdata\switches.go
--- Symlinking source file:
 C:\Users\wyvm3kp4\external\org_golang_x_tools\go\ssa\ssautil\visit.go -> D:\GoogleAGI\agi-master\agi-gofuse\src\golang.org\x\tools\go\ssa\ssautil\visit.go

5. cd D:\GoogleAGI\agi-master\agi-master
6. dlv exec ./bazel-bin/pkg/gapis.exe -- -enable-local-files -persist -rpc localhost:8888
result:   could not launch process: decoding dwarf section info at offset 0x0: too short

How can i debug it?

**Comment by official-minister** [comment]
GoPath:
D:\GoogleAGI\agi-master\agi-master>echo %GOPATH%
D:\GPUProfiler\gapid\gapid-master\gapid-gofuse

**Comment by official-minister** [comment]
D:\GoogleAGI\agi-master\agi-master>go version
go version go1.14.2 windows/amd64

**Comment by hevrard** [comment]
The agi-gofuse directory should be **outside** of the AGI git checkout, see https://github.com/google/agi/blob/master/DEVDOC.md#setup-golang-development:

```
# Prepare a agi-gofuse directory **outside of the AGI checkout directory**
mkdir <path-outside-agi-source>/agi-gofuse
```

Can you try to delete your `D:\GoogleAGI\agi-master\agi-gofuse` directory, re-create one as e.g. `D:\GoogleAGI\agi-gofuse`, and re-run the `//cmd/gofuse` command and update your gopath accordingly?
(Moving your existing `agi-gofuse` won't work, you do need to create a fresh one and run cmd/gofuse.)

**Comment by official-minister** [comment]
> The agi-gofuse directory should be **outside** of the AGI git checkout, see https://github.com/google/agi/blob/master/DEVDOC.md#setup-golang-development:
> 
> ```
> # Prepare a agi-gofuse directory **outside of the AGI checkout directory**
> mkdir <path-outside-agi-source>/agi-gofuse
> ```
> 
> Can you try to delete your `D:\GoogleAGI\agi-master\agi-gofuse` directory, re-create one as e.g. `D:\GoogleAGI\agi-gofuse`, and re-run the `//cmd/gofuse` command and update your gopath accordingly?
> (Moving your existing `agi-gofuse` won't work, you do need to create a fresh one and run cmd/gofuse.)

Thankyou very much, and My agi-gofuse dir is like this:
D: GoogleAGI
           |______agi-master
                             |________agi-gofuse
                             |________agi-master
                                                 |_______gpis
                                                 |_______gpit
                                                 |_______bazel-bin
                                                 |_______....

and I run build cmd in dir  D:\GoogleAGI\agi-master\agi-master
run dlv exec ./bazel-bin/pkg/gapis.exe  also in dir : D:\GoogleAGI\agi-master\agi-master
I think the path is correct.( I do follow the instruction: https://github.com/google/agi/blob/master/DEVDOC.md#setup-golang-development. because I dowonload the zip and unzip it, it has a agi-master dir outside.)

**Comment by official-minister** [comment]
Thankyou very much, and My agi-gofuse dir is like this:
D: GoogleAGI
|______agi-master
               |________agi-gofuse
               |________agi-master
                                     |_______gpis
                                     |_______gpit
|bazel-bin
|....

and I run build cmd in dir D:\GoogleAGI\agi-master\agi-master
run dlv exec ./bazel-bin/pkg/gapis.exe also in dir : D:\GoogleAGI\agi-master\agi-master
I think the path is correct.( I do follow the instruction: https://github.com/google/agi/blob/master/DEVDOC.md#setup-golang-development. because I dowonload the zip and unzip it, it has a agi-master dir outside.)

**Comment by official-minister** [comment]
> The agi-gofuse directory should be **outside** of the AGI git checkout, see https://github.com/google/agi/blob/master/DEVDOC.md#setup-golang-development:
> 
> ```
> # Prepare a agi-gofuse directory **outside of the AGI checkout directory**
> mkdir <path-outside-agi-source>/agi-gofuse
> ```
> 
> Can you try to delete your `D:\GoogleAGI\agi-master\agi-gofuse` directory, re-create one as e.g. `D:\GoogleAGI\agi-gofuse`, and re-run the `//cmd/gofuse` command and update your gopath accordingly?
> (Moving your existing `agi-gofuse` won't work, you do need to create a fresh one and run cmd/gofuse.)

Thankyou very much, and My agi-gofuse dir is like this:
D: GoogleAGI
-------|______agi-master
------------------|________agi-gofuse
------------------|________agi-master
--------------------------------|_______gpis
--------------------------------|_______gpit
|bazel-bin
|....

and I run build cmd in dir D:\GoogleAGI\agi-master\agi-master
run dlv exec ./bazel-bin/pkg/gapis.exe also in dir : D:\GoogleAGI\agi-master\agi-master

I think the path is correct.( I do follow the instruction: https://github.com/google/agi/blob/master/DEVDOC.md#setup-golang-development. because I dowonload the zip and unzip it, it has a agi-master dir outside.)

**Comment by hevrard** [comment]
Thanks for clarifying, so it looks like your `agi-gofuse` directory is outside of your source directory `D:\GoogleAGI\agi-master\agi-master`.

I think you issue comes from the fact that you did not build in **debug** mode: `bazel build -c dbg pkg`. Or, to mirror your command above:
```
bazel --host_jvm_args=-Djavax.net.ssl.trustStore="D:\JDK\jre\lib\security\cacerts" build -c dbg pkg
```

Can you give this a try, and let us know if it works?

**Comment by official-minister** [comment]
> Thanks for clarifying, so it looks like your `agi-gofuse` directory is outside of your source directory `D:\GoogleAGI\agi-master\agi-master`.
> 
> I think you issue comes from the fact that you did not build in **debug** mode: `bazel build -c dbg pkg`. Or, to mirror your command above:
> 
> ```
> bazel --host_jvm_args=-Djavax.net.ssl.trustStore="D:\JDK\jre\lib\security\cacerts" build -c dbg pkg
> ```
> 
> Can you give this a try, and let us know if it works?

**Comment by official-minister** [comment]
It  works, but I find another problem:
I use  "bazel build -c dbg pkg" to build debug program. And pkg is under the folder :D:\GoogleAGI\agi-master\agi-master\bazel-bin\pkg. It has agi.exe, gapis.exe....
Then I exce the cmd :  bazel --output_user_root="D:\\GoogleAGI\agi-master\build3" --host_jvm_args=-Djavax.net.ssl.trustStore="D:\JDK\jre\lib\security\cacerts" run //cmd/gofuse -- -dir **_D:\GoogleAGI\agi-master\agi-gofuse --bazelout="D:\GoogleAGI\agi-master\build3"._**

and I found D:\GoogleAGI\agi-master\agi-master\bazel-bin\pkg **_is deleted._** I check the dir,  **_D:\GoogleAGI\agi-master\agi-master\bazel-bin just has one folder: cmd and others all missed._**

so I exec debug cmd will have an error:
D:\GoogleAGI\agi-master\agi-master>dlv exec ./bazel-bin/pkg/gapis.exe -- -enable-local-files -persist -rpc localhost:8888
could not launch process: open ./bazel-bin/pkg/gapis.exe: The system cannot find the path specified.

In fact, I have tried to modify the "bazelout" param, but the result is the same.
 bazel --output_user_root="D:\\GoogleAGI\agi-master\build3" --host_jvm_args=-Djavax.net.ssl.trustStore="D:\JDK\jre\lib\security\cacerts" run //cmd/gofuse -- -dir D:\GoogleAGI\agi-master\agi-gofuse --bazelout=_**"D:\GoogleAGI\agi-master\agi-master\bazel-out".**_

Finally, I build my project again, and not exec bazel run \\cmd\\gouse.....（agi-gofuse has the compile result produced by last build.）,  and run delv directly, it can run debug model.

**Comment by official-minister** [comment]
bazel --output_user_root="D:\\GoogleAGI\agi-master\build3" --host_jvm_args=-Djavax.net.ssl.trustStore="D:\JDK\jre\lib\security\cacerts" run //cmd/gofuse -- -dir D:\GoogleAGI\agi-master\agi-gofuse --bazelout="D:\GoogleAGI\agi-master**_\build3\wyvm3kp4\execroot\gapid\bazel-out\x64_windows-dbg"_**

is the same. bazel-bin dir is clear except cmd

**Comment by official-minister** [comment]
> It works, but I find another problem:
> I use "bazel build -c dbg pkg" to build debug program. And pkg is under the folder :D:\GoogleAGI\agi-master\agi-master\bazel-bin\pkg. It has agi.exe, gapis.exe....
> Then I exce the cmd : bazel --output_user_root="D:\GoogleAGI\agi-master\build3" --host_jvm_args=-Djavax.net.ssl.trustStore="D:\JDK\jre\lib\security\cacerts" run //cmd/gofuse -- -dir **_D:\GoogleAGI\agi-master\agi-gofuse --bazelout="D:\GoogleAGI\agi-master\build3"._**
> 
> and I found D:\GoogleAGI\agi-master\agi-master\bazel-bin\pkg **_is deleted._** I check the dir, **_D:\GoogleAGI\agi-master\agi-master\bazel-bin just has one folder: cmd and others all missed._**
> 
> so I exec debug cmd will have an error:
> D:\GoogleAGI\agi-master\agi-master>dlv exec ./bazel-bin/pkg/gapis.exe -- -enable-local-files -persist -rpc localhost:8888
> could not launch process: open ./bazel-bin/pkg/gapis.exe: The system cannot find the path specified.
> 
> In fact, I have tried to modify the "bazelout" param, but the result is the same.
> bazel --output_user_root="D:\GoogleAGI\agi-master\build3" --host_jvm_args=-Djavax.net.ssl.trustStore="D:\JDK\jre\lib\security\cacerts" run //cmd/gofuse -- -dir D:\GoogleAGI\agi-master\agi-gofuse --bazelout=_**"D:\GoogleAGI\agi-master\agi-master\bazel-out".**_
> 
> Finally, I build my project again, and not exec bazel run \cmd\gouse.....（agi-gofuse has the compile result produced by last build.）, and run delv directly, it can run debug model.

and it has an error in this way
(dlv) break gapis/server/server.go:228
Command failed: could not find statement at gapis\server\server.go:228, please use a line with a statement

**Comment by hevrard** [comment]
Using `--output_user_root` will likely break the workflow, because it may change/delete some bazel-generated links.

To clarify, you do NOT have to run cmd/gofuse between `bazel build -c dbg pkg` and your call to delve. The only role of cmd/gofuse is to create a file hierarchy under agi-gofuse. You need to run this command *only once* when you setup the development. Once you have setup agi-gofuse, you should be able to:

1. Build in debug mode
2. Start debugging with delve

But you don't have to re-run cmd/gofuse in the middle. Also, you should NOT use `--output_user_root`, or change some Bazel arguments.

With this in mind, trying to reflect your commands, you should be able to run the following:

```
cd D:\GoogleAGI\agi-master\agi-master

bazel --host_jvm_args=-Djavax.net.ssl.trustStore="D:\JDK\jre\lib\security\cacerts" build -c dbg pkg

dlv exec ./bazel-bin/pkg/gapis.exe -- -enable-local-files -persist -rpc localhost:8888
```

Now, regarding your delve issue:

> (dlv) break gapis/server/server.go:228
> Command failed: could not find statement at gapis\server\server.go:228, please use a line with a statement

This is because there is currently no statement on this line: https://github.com/google/agi/blob/master/gapis/server/server.go#L228
I guess you tried this `file:line` because it is the one in the DEVDOC.md example, but this example is getting out of sync.

You should try a line with a statement, for example:
```
(dlv) break gapis/server/server.go:260
```

**Comment by official-minister** [comment]
Thank you! I solve the problem. It's so kind of you!
