### ISSUE TITLE
Build warning about Android NDK version

### ISSUE THREAD

**Issue by tobine** [google/agi#305]
**Environment information:**
 - AGI version: Latest master
 - Host OS: Windows

**Bug description**
When building on Windows I see the warning:

> WARNING: The major revision of the Android NDK referenced by android_ndk_repository rule 'androidndk' is 21. The major revisions supported by Bazel are [10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20]. Bazel will attempt to treat the NDK as if it was r20. This may cause compilation and linkage problems. Please download a supported NDK version.

This contradicts the build documentation that states:

> The minimum required version of the NDK is r21.

**Reproduction steps**
Pull latest code and build according to the [instructions](https://github.com/google/agi/blob/master/BUILDING.md)

**Comment by hevrard** [comment]
NDK r21 is not yet supported in Bazel, see: https://github.com/bazelbuild/bazel/issues/10811

Still, we're using it to have access to the unified Khronos validation layer. We never had an NDK-related issue after the update to r21, so I think it's safe to ignore this warning.

What is left to do is to ass to our build documentation that this warning is expected, I'll take care of that.

**Comment by hevrard** [comment]
Fixed by: #307
