### ISSUE TITLE
Bazel build errors "'string' object is not callable"

### ISSUE THREAD

**Issue by tobine** [google/agi#306]
**Environment information:**
 - AGI version: Latest master
 - Host OS: Windows

**Bug description**
When building the latest AGI on Windows I hit two separate errors stating:

> 'string' object is not callable

I'm able to fix both of these errors by removing paren chars "()" in two "cc_toolchain.strip_executable()" lines. The full error messages are below.

Is this a tool versioning issue? When I run "bazel --version" the output is "bazel 2.2.0"

**Reproduction steps**
Pull the latest master code on Windows and build according to [instructions](https://github.com/google/agi/blob/master/BUILDING.md)

**Stacktrace**

First Error:

> C:\src\agi>bazel build pkg
> ERROR: C:/src/agi/core/vulkan/vk_virtual_swapchain/cc/BUILD.bazel:75:1: in strip rule //core/vulkan/vk_virtual_swapchain/cc:libVkLayer_VirtualSwapchain_stripped.dll:
> Traceback (most recent call last):
>         File "C:/src/agi/core/vulkan/vk_virtual_swapchain/cc/BUILD.bazel", line 75
>                 strip(name = 'libVkLayer_VirtualSwapchain_stripped.dll')
>         File "C:/src/agi/tools/build/rules/cc.bzl", line 62, in _strip_impl
>                 ctx.actions.run(<4 more arguments>)
>         File "C:/src/agi/tools/build/rules/cc.bzl", line 63, in ctx.actions.run
>                 cc_toolchain.strip_executable()
> 'string' object is not callable
> ERROR: Analysis of target '//:pkg' failed; build aborted: Analysis of target '//core/vulkan/vk_virtual_swapchain/cc:libVkLayer_VirtualSwapchain_stripped.dll' failed; build aborted
> INFO: Elapsed time: 1.595s
> INFO: 0 processes.
> FAILED: Build did NOT complete successfully (0 packages loaded, 0 targets configured)

Second Error (after fixing first by removing "()"):

> ERROR: C:/src/agi/gapidapk/android/apk/BUILD.bazel:33:1: in _strip rule //gapidapk/android/apk:armeabi-v7a_deviceinfo:
> Traceback (most recent call last):
>         File "C:/src/agi/gapidapk/android/apk/BUILD.bazel", line 33
>                 _strip(name = 'armeabi-v7a_deviceinfo')
>         File "C:/src/agi/gapidapk/android/apk/rules.bzl", line 23, in _strip_impl
>                 ctx.actions.run(<4 more arguments>)
>         File "C:/src/agi/gapidapk/android/apk/rules.bzl", line 24, in ctx.actions.run
>                 cc_toolchain.strip_executable()
> 'string' object is not callable
> ERROR: Analysis of target '//:pkg' failed; build aborted: Analysis of target '//gapidapk/android/apk:armeabi-v7a_deviceinfo' failed; build aborted
> INFO: Elapsed time: 81.173s
> INFO: 0 processes.
> FAILED: Build did NOT complete successfully (286 packages loaded, 24257 targets configured)

**Comment by hevrard** [comment]
> Is this a tool versioning issue? When I run "bazel --version" the output is "bazel 2.2.0"

You should use Bazel **2.0.0**. Can you double check the version and try with bazel 2.0.0 ?

**Comment by pau-baiget** [comment]
@tobine is this issue still relevant to you? Otherwise, can you please close it? Thanks!

**Comment by tobine** [comment]
No longer see this issue
