### ISSUE TITLE
question about memory_tracker layers

### ISSUE THREAD

**Issue by official-minister** [google/agi#334]
Hello, friend. I have used gapid and capture trace with memory_tracker config, but I can't parsing trace file by using agi.
I find that the branch of perfetto is different.
And I find agi set memory_tracker with false in
core\os\device\deviceinfo\cc\android\query.cpp.

Then I set it to be true. And I can capture with this config and produce a trace file. But I can't open the file and gapis will coredump. Then I think gapis stopped while loadcapture is operating and trace_processor parse failed.

Is this the reason you disable the vulkan_memory_tracker module? Or how can I fix it?
Thank you.

**Comment by hevrard** [comment]
Hi @official-minister, apologies for the delay.

The memory tracker in `core/memory_tracker/` is an optimization to reduce the size of our graphics traces. As there is some bad interactions with perfetto trace processor, it might be disabled in some cases.

Now, you may refer to `core/vulkan/vk_memory_tracker_layer/` : this is a vulkan layer prototype that has severe limitations, and we disabled it altogether. We are currently exploring alternative ways to track graphics memory.

**Comment by official-minister** [comment]
I find bugs in perfetto and propose a issue. Maybe you can provide a error trace file for them:
https://github.com/google/perfetto/issues/34

**Comment by hevrard** [comment]
Thanks for the pointer to the perfetto issue. We need to clarify a few things to precisely understand what's going on:

1. Which version do you use to capture the trace? (GAPID or AGI, and which commit?)

2. On which device do you capture the trace, with which GPU driver version?

3. Which AGI/GAPID version do you use to open the trace? (GAPID or AGI, and which commit?)

4. Can you share the gapis coredump that you get, or any kind of stack trace?

5. Can you share the perfetto trace? (You can attach it to a github message. If github refuse to upload it, you can try to zip it and upload the zip version).

**Comment by pau-baiget** [comment]
@official-minister this bug's been stuck waiting to get more information for a few months so we are proceeding to close it now. If you can provide more information as requested by @hevrard , please re-open it and we'll take action. I recommend you try the[ latest developer release of AGI](https://github.com/google/agi-dev-releases/releases/) which contains lots of fixes since your bug was originally reported. Thank you!!
