### ISSUE TITLE
remote question about gapis and gapit

### ISSUE THREAD

**Issue by official-minister** [google/agi#391]
I noticed that gapis is a server and gapit is a client. I want to start gapis on machine A (addr A ), and start gapit on machine B (addr B). Then I use gapit communicate with gapis. How can I do it?
Maybe like this:
addr A cmd: gapis.exe -rpc A:8888
addr B cmd: gapit.exe ???

I tried to use "telnet A:8888" on  addr B after start gapis on A, but failed.

**Comment by johnplate** [comment]
As gapit is a pure command line tool, it is currently not supported to use it with a server on a remote machine. You can use a remote shell from machine B to start gapit on machine A and to use an existing server:
addr A cmd: gapis.exe -persist -rpc A:8888
addr A cmd: gapit.exe <verb> -gapis-port 8888 <verb args>

Alternatively you can use ssh port forwarding to run gapit on machine B with a port that is forwarded to machine A.
You can find the flag -gapis-port with gapit <verb> -fullhelp, e.g. gapit trace -fullhelp.
