### ISSUE TITLE
Opening traces via Finder launches multiple AGI instances and it can get stuck

### ISSUE THREAD

**Issue by pmuetschard** [google/agi#458]
On MacOS, when opening files from within Finder, while an AGI instance is already running, each time a trace file is double-clicked/opened, instead of opening that file within the already running instance, a new AGI instance is launched.  This often/always results in a stuck situation, where the AGI icon keeps bouncing in the Dock, but no progress is made. When getting into this stuck mode, attempting to double-click any other file, no longer launches a new AGI instance, which makes it impossible to open any more files. When it gets stuck, you can no longer launch AGI, even by double-clicking the App.

**Comment by pmuetschard** [comment]
Work-arounds to get out of the stuck mode:

1. Launch AGI via the command line `/Applications/AGI.app/Contents/MacOS/agi`. However, the Dock remains broken.
2. `sudo killall launchservicesd; sudo killall Dock` This is a bit brutal, but appears to work. I have noticed that the Dock misbehaves a bit afterwards (e.g. it stays visible on top of fullscreen content).

**Comment by pmuetschard** [comment]
It appears, at least sometimes, that right-clicking on the bouncing icon and selecting "Force Quit" also recovers the system. It can take ~5 seconds after selecting "Force Quit" for the bouncing icon to go away and the system to recover.

**Comment by pau-baiget** [comment]
Lowering priority since we have a workaround stated in comment 2.

**Comment by zhangyiwei** [comment]
@zhangyiwei cc myself here.
