### ISSUE TITLE
The server has exited with an error code of: 2 

### ISSUE THREAD

**Issue by davidenitti** [google/agi#476]
**Environment information:**
 - AGI version: agi-1.0.0
 - Host OS: Ubuntu

**Bug description**
when I start agi I get 
The application encountered an error:
The server has exited with an error code of: 2 
Most functions in AGI are unavailable without a server. 
You can restart the server, exit AGI, or close the dialog to continue without a server.
Please check the logs for details.

**Reproduction steps**
start agi

**Stacktrace**
```
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xaa4e44]

goroutine 34 [running]:
github.com/google/gapid/core/app/crash.Crash(0x3b01d60, 0x73c8770)
	core/app/crash/crash.go:89 +0xb1
github.com/google/gapid/core/app/crash.handler()
	core/app/crash/crash.go:56 +0x52
panic(0x3b01d60, 0x73c8770)
	GOROOT/src/runtime/panic.go:967 +0x15d
github.com/google/gapid/core/os/android/adb.newDevice(0x4a258a0, 0xc00023c390, 0xc00007b549, 0x8, 0x2, 0x0, 0x0, 0x0)
	core/os/android/adb/device.go:255 +0x824
github.com/google/gapid/core/os/android/adb.scanDevices(0x4a258a0, 0xc00023c390, 0x0, 0x0)
	core/os/android/adb/device.go:291 +0x33d
github.com/google/gapid/core/os/android/adb.Devices(0x4a258a0, 0xc00023c390, 0x0, 0x0, 0x0, 0x0, 0x0)
	core/os/android/adb/device.go:106 +0x39
main.monitorAndroidDevices.func1(0xc000223798, 0x4a258a0, 0xc00023c390, 0xc00023c0c0)
	cmd/gapis/main.go:163 +0x76
main.monitorAndroidDevices(0x4a258a0, 0xc00023c390, 0xc00023c0c0, 0xc000223798)
	cmd/gapis/main.go:169 +0x4d
main.run.func1()
	cmd/gapis/main.go:122 +0x63
github.com/google/gapid/core/app/crash.Go.func1(0xc000237aa0)
	core/app/crash/crash.go:65 +0x49
created by github.com/google/gapid/core/app/crash.Go
	core/app/crash/crash.go:63 +0x3f

```

**Screenshots**

![image](https://user-images.githubusercontent.com/7438184/94540445-c5892d80-0246-11eb-88e9-4559a465473b.png)

**Additional debugging information**
[gapis.log](https://github.com/google/agi/files/5297849/gapis.log)
[gapic.log](https://github.com/google/agi/files/5297850/gapic.log)

**Comment by hevrard** [comment]
@davidenitti thanks for reporting, I've proposed a patch to avoid such segfaults: https://github.com/google/agi/pull/477

Looking at the gapis.log your provided, it sounds like AGI fails to install its APK on the device:
```
09:21:11.399 I: [Try ABI: arm64-v8a⇒gapidapk.EnsureInstalled] <gapis> Installing gapid.apk
   Cause: Process returned error
   Cause: exit status 1
```

Can you double-check that you authorized adb USB debugging on the device?

Please check all device requirements as documented on: https://gpuinspector.dev/docs/requirements

**Comment by davidenitti** [comment]
I'm using POCO F2 Pro (with Qualcomm Snapdragon 865).
I enabled USB debugging, but not install via usb. is this the problem? do I need to root the phone?
thanks

**Comment by hevrard** [comment]
You will need to allow for install via usb, yes. Thanks for this feedback, we probably need to clarify this in our documentation!

Note that only Pixel4 is currently supported. There is a discussion for support of Realme X2 Pro here: https://github.com/google/agi/issues/462

If you want to ask for support of POCO F2 Pro, please open a new issue.
