### ISSUE TITLE
Copy or export selection data as CSV or TSV

### ISSUE THREAD

**Issue by SimHacker** [google/agi#496]
Useful feature request, please:

**Environment information:**
 - AGI version: 1.0
 - Host OS: Mac

**Bug description**
It would be wonderful to be able to copy the two dimensional tables of numbers in the selection panel as a CSV or TSV file that I could easily paste into Google Sheets, Excel, etc. 

Also, is there a way to automate exporting such data from the trace files with the the gapit command line utility? The documentation and examples are a bit sparse...  

**Reproduction steps**
Capture a trace. Go into selection mode. Drag a rectangle over multiple rows and columns. See the data displayed in a table in the selection window at the bottom of the window. Try to select the data. You can only select one row at a time, and you can't copy the data. Ideally I would like to select all or any of the cells using standard selection commands, and then copy it as a CSV or TSV file to the clipboard. (Needs to be a way to select between CSV and TSV, which is useful for Google Sheets.) Being able to easily copy data from AGI into Google Sheets will make me joyful!

**Comment by pmuetschard** [comment]
Thanks for the suggestion. It sounds reasonable and we'll prioritize.

As for getting the data using CLI, you can do so via `gapit perfetto`, but it'll require you to write the SQL queries against the Perfetto tables yourself... You can see all the queries the UI runs by running it with debug logging on, but be aware that the UI creates a lot of view and SQLite virtual tables, so you might have to do a lot of back-tracking from the queries run when selecting things in the UI. You can use the query viewer in the UI to run queries to explore the schema and data.

**Comment by SimHacker** [comment]
Thank you for this great tool, and for your openness to suggestions!

**Comment by ttanatb** [comment]
Closing this issue as we do not have the bandwidth to explore/support this usecase
