### ISSUE TITLE
Bazel build with error "PKIX path building failed"

### ISSUE THREAD

**Issue by zuz19920624** [google/agi#576]
When I try to build with bazel, I occured the problem of ssl certification problem. I added the CA certificate of the website to JAVA but it still doesn't work. It occurs on ubuntu 16.04 and windows 10 platform. 

![image](https://user-images.githubusercontent.com/42440887/100192894-b9130f80-2f2d-11eb-83aa-0a984bd4f26c.png)

Download from https://codeload.github.com/bazelbuild/bazel-gazelle/zip/9b9f0226e01d10a70cbf268f9967cb715c8ff067 failed: class javax.net.ssl.SSLHandshakeException PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target.

**Comment by pmuetschard** [comment]
Make sure your `$JAVA_HOME/lib/security/cacerts` is valid. If it is and seems to contain the certificates needed, there may be a machine-in-the-middle scenario going on trying to spy on SSL traffic and replacing certs in the handshake. This is not an AGI issue.
