### ISSUE TITLE
Cannot find any device via USB although can get log via terminal adb on Debian

### ISSUE THREAD

**Issue by WesleyKhoiVo** [google/agi#587]
**Environment information:**
 - AGI version: 1.0 (openJDK 8), 0.10.0 (openJDK 11)
 - Host OS: Debian 10 Buster
 If tracing on Android:
 - Device model: Sony Z5, Amazon Fire Tablet HD 8 Gen 7th
 - Android Version: 7.0 (Sony Z5), 5.1 (Amazon)

**Bug description**
Cannot find any device via USB although I can get log via terminal adb on Debian

**Reproduction steps**
Install any version AGI, open AGI, setup ADB path, open AGI, cannot find any device

**Screenshots**
![image](https://user-images.githubusercontent.com/20337876/101311029-08890200-3883-11eb-8077-a011702692f8.png)
Left image, I open terminal and use adb command. Right image, AGI cannot find any device. Two windows is opened side by side at the same time
![image](https://user-images.githubusercontent.com/20337876/101311132-5a318c80-3883-11eb-9c7f-d8adc60d2820.png)
ADB path I setup.

**Additional debugging information**
[gapic.log](https://github.com/google/agi/files/5650517/gapic.log)
[gapis.log](https://github.com/google/agi/files/5650518/gapis.log)

Thanks

**Comment by lpy** [comment]
Please refer to https://gpuinspector.dev/docs/devices for a list of supported devices and OS version.
