### ISSUE TITLE
Timeout connecting to service

### ISSUE THREAD

**Issue by codevania** [google/agi#609]
**Environment information:**
- AGI version: Version 1.0.0:4ddd08c5546200a14141b75639a4b758fb2fadd2
 - Host OS: Windows 10
 If tracing on Android:
 - Device model: SM-G986N
 - Android Version: Android 11 API 30 - Qualcomm Adreno (TM) 650

**Bug description**
I could not select Application to debug.

**Reproduction steps**
* 'Select an Application to Trace' dialog does not response.

**Stacktrace**
Please paste a stacktrace here if it's available. - No Crash Occurred

**Screenshots**
![AGI Timeout connecting to service 2020-12-22 142459](https://user-images.githubusercontent.com/2435606/102852485-b5f23d00-4461-11eb-8383-178a94cda813.png)

**Additional debugging information**
[gapic.log](https://github.com/google/agi/files/5727978/gapic.log)

**Comment by hevrard** [comment]
Thanks for reporting!

Could you let us know if you can reproduce with the latest dev-release version available from: https://github.com/google/agi-dev-releases/releases/latest

If you can reproduce with the latest dev-release, can you upload the gapic.log and gapis.log temporary files?

**Comment by codevania** [comment]
Thank you @hevrard~ It works fine.
But I could not find the way how to symbolicate our source code. Please let me know if it is possible.
Thanks anyway, and I would look forward to the next update for 'single frame capture' :)
