### ISSUE TITLE
Plz support for OPPO Reno5

### ISSUE THREAD

**Issue by klkucan** [google/agi#615]
This device is Android 11,  Qualcomm SDM765.

**Comment by jakon2048** [comment]
Hi, Oppo is currently looking into supporting Reno 5 Pro+, which is based on the 865 chipset. 

I don't think they are currently looking into supporting the Reno5, but I will raise this with them.

**Comment by klkucan** [comment]
> Hi, Oppo is currently looking into supporting Reno 5 Pro+, which is based on the 865 chipset.
> 
> I don't think they are currently looking into supporting the Reno5, but I will raise this with them.

thx
