### ISSUE TITLE
When to Support Qualcomm® Adreno™ 618

### ISSUE THREAD

**Issue by yaochx** [google/agi#616]
For a long period, the supported device list is not updated.
Could anyone to tell me when to Support Qualcomm® Adreno™ 618?

Thanks in advance.
Collin

**Comment by jakon2048** [comment]
Hi, which device are you looking for support?

**Comment by yaochx** [comment]
> Hi, which device are you looking for support?
Hi, jakon2048
I need support for "Google Pixel 4a | Qualcomm® Adreno™ 618".

**Comment by jakon2048** [comment]
The supported device list will be updated, but Pixel 4a should be supported if you have the latest December update.

**Comment by yaochx** [comment]
> The supported device list will be updated, but Pixel 4a should be supported if you have the latest December update.
That‘s awesome, Let me have a try
