### ISSUE TITLE
Pixel 4A Device Not supported

### ISSUE THREAD

**Issue by rosasco-wk** [google/agi#632]
Using the open beta: 1.0.0:4ddd08c5546200a14141b75639a4b758fb2fadd2 with a Pixel 4A running Android 11, I get an unsupported device error when following the prescribed getting started steps:

<img width="682" alt="Screen Shot 2021-01-11 at 4 40 44 PM" src="https://user-images.githubusercontent.com/57770425/104254643-1c98c400-542c-11eb-8c1a-7cc1d0d2a91c.png">

**Comment by hevrard** [comment]
@rosasco-wk thanks for reporting!

Can you double check that you have the latest Android update installed on your device?

Then, if it still fails, can you give us the device build fingerprint (the output of `adb shell getprop ro.system.build.fingerprint`)?

**Comment by rosasco-wk** [comment]
adb shell getprop ro.system.build.fingerprint ==>> "google/sunfish/sunfish:11/RP1A.200720.011/6746289:user/release-keys"

**Comment by rosasco-wk** [comment]
My device is reporting *Couldn't Update* *installation problem* "This is an early OTA for Googlers to update ...", i.e. dogfood related stuff.  What further steps can I take to provide you more info @hevrard ?

**Comment by lpy** [comment]
Hi John, could you please bring this thread to our internal bug component so that we can share more information? Thanks!
