### ISSUE TITLE
Device validation fails on supported device

### ISSUE THREAD

**Issue by DavidDomkar** [google/agi#636]
**Environment information:**
 - AGI version: v1.1.0-dev-20210110, also tried latest stable version
 - Host OS: Windows
 If tracing on Android:
 - Device model: Samsung Galaxy Note 10+
 - Android Version: 11

**Bug description**
AGI shows that the support validation of my device failed.

**Reproduction steps**
Open AGI, select capture new trace, select the connected device from the dropdown menu.

**Screenshots**
![image](https://user-images.githubusercontent.com/7688351/104751858-3b61c800-5756-11eb-993e-a4d9ca1ea7e7.png)

**Additional debugging information**
[logcat-full.txt](https://github.com/google/agi/files/5821761/logcat-full.txt)

**Comment by hevrard** [comment]
@DavidDomkar thanks for reporting!

Can you double-check that you have the latest Android system update on that device?

If your device still doesn't pass validation after that, can you give us the Android build fingerprint (output of `adb shell getprop ro.build.fingerprint`)?

And can you also run this command while having only your Note10+ plugged in your host PC (the `gapit` tool can be found in AGI's install directory), and upload the resulting log here?
`gapit validate_gpu_profiling -os android`

**Comment by DavidDomkar** [comment]
Hello, thanks for getting back to me. 

I can confirm that I have the latest system update. I am attaching more information in hopes of resolving this.

The output of the build fingerprint command: `samsung/d2seea/d2s:11/RP1A.200720.012/N975FXXU6ETLL:user/release-keys`

The output from the gapit tool: [output.txt](https://github.com/google/agi/files/5821936/output.txt)

**Comment by DavidDomkar** [comment]
Any updates on this?

**Comment by pmuetschard** [comment]
Sorry, we've mistakenly marked the Mali versions of these phones as supported. Samsung has not yet released the driver support needed for profiling on these devices. See #652 and #654 for more information.
