### ISSUE TITLE
There is no "Frame" option in "Capture System Profile" when connect the phone.

### ISSUE THREAD

**Issue by t-m-k** [google/agi#648]
**Environment information:**
 - AGI version: **1.0.0**
 - Host OS: **win10**
 If tracing on Android:
 - Device model:**oppo find Qualcomm® Adreno™ 650**
 - Android Version: **android 11 api 30**

**Bug description**
**There is no "Frame" option in "Capture System Profile" when connect the phone.**

**Screenshots**
![image](https://user-images.githubusercontent.com/20682161/105455123-f5f54b80-5cbd-11eb-8adf-7736bd402f18.png)

**Comment by hevrard** [comment]
Yes, there is no "frame" option in the "Start" field when you're doing a system profile. During a system profile, AGI just profiles all activities on the phone, it does not look into the graphics API calls of the game, so it cannot count frames.

I believe most users just pick the "Manual" option, so they can manually decide when to start the system profile.
