### ISSUE TITLE
Frame capture: 1-draw-call difference in images between glDrawElements and vkCmdDrawIndexed

### ISSUE THREAD

**Issue by ianelliottus** [google/agi#669]
Note: This is described w.r.t. FIFA Soccer, but is true for all GLES games/applications.

Describe the issue:

- This may be an issue with other games, but I just noticed it.
- Looking at my frame capture of FIFA Soccer, I sometimes click on the a higher-level glDrawElements node, and sometimes I click on the GLES and/or Vulkan nodes underneath. For the same higher-level glDrawElements, I get different images for the GLES and Vulkan nodes.

Expected behavior:

- When I open and select different nodes of a frame capture of a GLES app, I expect the same image to be seen regardless of whether I am clicking on the GLES or Vulkan nodes

Actual behavior:

- I am seeing one-draw-call difference between the "OpenGL ES Commands" and the "DrawIndexed" hierarchies. Since a small thumbnail is included on some of the hierarchy, I started looking at the draws before and after big changes. That's when I noticed this.

Repro steps:

- With the capture that I point to (below), look at when the draws in the 2nd RenderPass change from black to green. Here's what the hierarchy looks like:
  - Host Coordination
  - vkQueueSubmit
    - pSubmits[0]
      - Command Buffer
        - Render Pass
        - Render Pass
          - glDrawElements
          - glDrawElements
          - glDrawElements
          - glDrawElements
          - glDrawElements
          - glDrawElements
          - glDrawElements
            - vkCmdBeginDebugUtilsLabelEXT
              - OpenGL ES Commands
                - vkCmdBeginDebugUtilsLabelEXT
                - gl*
                - ...
                - glDrawElements
                - vkCmdEndDebugUtilsLabelEXT
              - DrawIndexed
                - vkCmdBindPipeline
                - ...
                - vkCmdDrawIndexed
              - vkCmdEndDebugUtilsLabelEXT
            - glDrawElements
              - vkCmdBeginDebugUtilsLabelEXT
              - OpenGL ES Commands
                - vkCmdBeginDebugUtilsLabelEXT
                - gl*
                - ...
                - glDrawElements
                - vkCmdEndDebugUtilsLabelEXT
              - DrawIndexed
                - vkCmdBindPipeline
                - ...
                - vkCmdDrawIndexed
              - vkCmdEndDebugUtilsLabelEXT
            - glDrawElements
            - ...

- I chose those particular parts of the hierarchy because that's where the green soccer field first gets drawn.
- If you open up the "OpenGL ES Commands" and the "DrawIndexed" nodes above, and click on the lower-level glDrawElements and vkCmdDrawIndexed nodes. You will see that the GLES draw doesn't show the same image as the Vulkan draw.

Versions:

- AGI: v1.1.0-dev-20210110
- ANGLE (pre-built): <ANGLE version doesn't matter>
- App version: versionCode=754 minSdk=23 targetSdk=29

**Comment by vinjn** [comment]
@ianelliottus how did you manage to do frame capture with API sequences, I can only gather performance counters.
