### ISSUE TITLE
samsung SM-G9708- Android 10 API 29 Adreno (TM)640 验证失败 Deivce support validation failed

### ISSUE THREAD

**Issue by SirXuNian** [google/agi#683]
**Environment information:**
 - AGI version: 
 - Host OS: [e.g. Linux]
 If tracing on Android:
 - Device model:  samsung SM-G9708
 - Android Version: Android 10 

**Bug description**
Deivce support validation failed

**Reproduction steps**

**Stacktrace**
Please paste a stacktrace here if it's available.

**Screenshots**

**Additional debugging information**
- Please attach the generated _gapis.log_ and _gapic.log_ files you will find in the temp folder (e.g. /tmp/ on linux).
- If using Android: Please attach a full logcat dump (```adb logcat -d > logcat-full.txt```) that contains logs since AGI was started.

**Comment by lpy** [comment]
I think I am going to need more information. Did you get the developer driver from Qualcomm? etc

**Comment by lpy** [comment]
Please feel free to reopen the issue with more actionable information
