### ISSUE TITLE
Is there any method to catch AGI trace when the target application is not debuggable

### ISSUE THREAD

**Issue by Huanhuan006** [google/agi#688]
**Environment information:**
 - AGI version:1.0.0
 - Host OS: Windows 10
 If tracing on Android:
 - Device model: Google Pixel 5
 - Android Version:11

**Bug description**
Could not select some applications

**Reproduction steps**
1.Open AGI 1.0.0
2.Click on the “…” button right next to the “Application” text entry to list applications that can be traced on the selected device.
--->Only there applications are shown.(There are lots of applications on my devices)

Questions:
I think the other applications which not shown are not debuggable( android:debuggable="true")
Does this means I can't use AGI to catch a third party application trace?

**Comment by hevrard** [comment]
You are correct, AGI can only trace debuggable apps, this is documented in the requirements:
https://gpuinspector.dev/docs/requirements

**Comment by Huanhuan006** [comment]
Dear hevrard,
Thanks for your replay.
1.When does this feature **Dive deep into a single frame** will be ready？
In https://gpuinspector.dev/,it shows the feature will coming soon
2.I can't see any Mediatek devices in **Supported Devices** both with Arm® Mali™, and Imagination® PowerVR™ GPU, what should I provide to request AGI support for different Mediatek devices?

**Comment by hevrard** [comment]
Dive deep into a single frame: we're working on it, but there's no release date yet.

For support of devices, please open a dedicated issue for the particular device you want to be supported.

**Comment by Huanhuan006** [comment]
Dear hevrard,
Any update of Dive deep into a single frame? Thanks.

**Comment by jakon2048** [comment]
Hi Huanhuan, while we cannot give an exact date, we are hoping it will be sometime soon this year! Thank you!

**Comment by Huanhuan006** [comment]
Thanks Jay

**Comment by Huanhuan006** [comment]
Got it,thanks.
