### ISSUE TITLE
vkCmdClearAttachments not under glDrawElements hierarchy

### ISSUE THREAD

**Issue by ianelliottus** [google/agi#696]
**Environment information:**
 - AGI version: 1.1.0:dev-20210127-3678b588413bc6da5cdd54235aeef4ce895f8ffb
 - Host OS: Linux
 If tracing on Android:
 - Device model: Pixel 4 XL
 - Android Version: pre-release Android S

**Bug description**
Replaying a trace with "Car Parking Multiplayer" (now that an ANGLE fix allows the game to be played), the vkCmdClearAttachments commands are not under the glDrawElements hierarchy, but are peers of the glDrawElements commands.

NOTE: I can send you an AGI trace (github won't let me attach it).

**Reproduction steps**
1) Obtain latest ANGLE APK, "Car Parking Multiplayer" game, and AGI
2) Do an AGI frame capture while driving
3) Open the trace and open the hierarchy of command buffers and render passes.
4) Observe that vkCmdClearAttachments is a peer of glDrawElements, not underneath it

**Screenshots**
Attached is a screenshot that shows a number of glDrawElements calls with a vkCmdClearAttachments call in the middle.  I opened up the next glDrawElements call to show that the GLES app was trying to clear the depth and stencil buffers (which led to the vkCmdClearAttachments call.

![Screenshot from 2021-03-01 13-50-39](https://user-images.githubusercontent.com/16325331/109557356-3b632080-7a95-11eb-8663-757c431c788b.png)

**Comment by pmuetschard** [comment]
This is an ANGLE issue. The `glDrawElements` marker that contains the `glClear*` commands is issued after the `vkCmdClearAttachments`. If you want the clear command to be part of the group, the push marker has to be issued before the `vkCmdClearAttachments` command.

**Comment by ianelliottus** [comment]
This also affects Hearthstone.

In considering this more, I agree that this is an ANGLE issue.  The problem is that ANGLE combines some clears with the start of a render pass, and sometimes does the clear as a separate Vulkan command (i.e. within a render pass).  ANGLE issues the Vulkan debug-util markers at a higher level than and sooner than where the decision is made for how a clear should be processed.

I'm going to close this bug, and open an ANGLE bug.
