### ISSUE TITLE
GLES Compute dispatching messes up CommandTree hierarchy

### ISSUE THREAD

**Issue by ianelliottus** [google/agi#697]
**Environment information:**
- AGI version: 1.1.0:dev-20210127-3678b588413bc6da5cdd54235aeef4ce895f8ffb
  - Host OS: Linux
If tracing on Android:
- Device model: Pixel 4 XL
- Android Version: pre-release Android S

**Bug description**

Replaying a frame capture of "Ragnarok M: Eternal Love" (with latest ANGLE that fixes a transparency bug) game-play results in a CommandTree hierarchy that is messed up.  The root cause seems to be GLES compute dispatching

NOTE: I can send you an AGI trace (github won't let me attach it).

**Reproduction steps**

1) Contact me and I'll send you a trace file
  OR
1) Obtain latest ANGLE APK, "Ragnarok M: Eternal Love" game, and AGI
  a) The game likes to download an additional 1.9 GB worth of content (seems like at least once a week)
2) Do an AGI frame capture and press "Start" after in game-play (requires pressing a Start or Play type button on two different screens)
3) Open the trace and open the hierarchy of command buffers and render passes.
4) Observe that the hierarchy underneath a glDispatchCompute may contain multiple levels of other commands (including draws and other dispatches).

**Screenshots**

The following screenshot shows multiple levels of dispatch and draw commands under a higher-level dispatch command.

![Screenshot from 2021-03-01 16-20-59](https://user-images.githubusercontent.com/16325331/109572273-28a71680-7aaa-11eb-8344-225720b589d8.png)

**Comment by pmuetschard** [comment]
This looks like an issue with the ANGLE debug markers. Can you confirm that the glDispatchCompute marker is popped at the right time? It looks like the pops are missing/too late. If not, i.e. if they are emitted at the right time (the first one should be right before the vkPipelineBarrier, or at least before the push of the next glDispatchCompute marker), then it's a bug in our debug marker command grouping when building the tree in gapis.

**Comment by ianelliottus** [comment]
Mark fixed this with the following ANGLE CL: https://chromium-review.googlesource.com/c/angle/angle/+/2930818
