### ISSUE TITLE
make-debuggable fails when jarsigner path does not match java version

### ISSUE THREAD

**Issue by mattyclarkson** [google/agi#71]
If `make-debuggable` is ran with the `-jarsigner` set to a different version of the Java, it can fail with:

```
jarsigner error: java.time.DateTimeException: Invalid value for MonthOfYear (valid values 1 - 12): 0
```

`make-debuggable` should run the `jarsigner` command with `JAVA_HOME` set to the same Java home that `jarsigner` lives in.

In `core/os/android/apk/debugifier.go` the following changes need to be made:
1. `execCommand` needs to accept an environment variable map
2. `jarSign` needs to determine `JAVA_HOME` constructed from the `jarsigner` path given
3. `jarSign` needs to pass the `JAVA_HOME` along with the `jarsigner` `execCommand` call

Finding `JAVA_HOME` could be found with _something_ like:
```
jarSignPath, err := exec.LookPath(a.JarSignCmd)
if err != nil {
  return err
}
jarSignResolved, err := os.ReadLink(jarSignPath)
if err != nil {
  return err
}
env := map[string]string{
    "JAVA_HOME": filepath.Dir(filepath.Dir(jarSignResolved)),
}
```

**Comment by pau-baiget** [comment]
Matt, thanks for your reporting this issue. Since you already have a proposed change, would you be able to create a PR that we can review?

**Comment by mattyclarkson** [comment]
Would be happy to once I get legal approval.

**Comment by pau-baiget** [comment]
Since you've got a workaround we're assigning a low priority for now. We'll revisit after GDC.
