### ISSUE TITLE
Support of POCO F2 Pro

### ISSUE THREAD

**Issue by sergii-psp** [google/agi#733]
Please add support 
 - Host OS:Linux
 - Device model: POCO F2 Pro
 - Android Version: 11

**Comment by jakon2048** [comment]
Will reach out to Xiaomi to see if they have any interest.

**Comment by sergii-psp** [comment]
Graphics API Debugger 1.6.1  works with OpenGL ES 2 on POCO F2 Pro.
Expecting AGPI also can do it (device recognized but not allow to start) and provide more features.

**Comment by jakon2048** [comment]
That's the intended goal. However, for AGI to work, the driver of the device needs to be updated to siphon out profiling information (e.g. GPU counters). Devices need update to their GPU driver firmware to support this and OEMs control that.
