### ISSUE TITLE
Wrong image shown for PUBG MOBILE LITE frame capture

### ISSUE THREAD

**Issue by ianelliottus** [google/agi#740]
**Environment information:**
 - AGI version: agi-1.1.0-dev-20210318
 - Host OS: gLinux
 If tracing on Android:
 - Device model: Pixel 4 (flame), but problem seen on Pixel 4 XL 3+ months ago
 - Android Version: Android 11 latest quarterly patch release (RQ2A.210305.006)

**Bug description**
Replaying a GLES frame capture of PUBG MOBILE LITE and clicking on any draw command (or the final vkQueuePresentKHR) shows an 8x8 color image instead of the actual color image contents.  The correct depth-buffer image is shown

**Reproduction steps**
1) Open a trace from gameplay
2) Click on "vkQueuePresentKHR" and/or any glDraw* command under the 2nd vkQueueSubmit hierarchy.  Observe that the color image is 8x8 and that the depth image is more-reasonably sized (e.g. 536x1136 on my Pixel 4).

**Screenshots**

![Screenshot from 2021-03-22 17-00-05](https://user-images.githubusercontent.com/16325331/112068711-1dd32500-8b30-11eb-98a8-33b912b7293d.png)
![Screenshot from 2021-03-22 17-00-11](https://user-images.githubusercontent.com/16325331/112068717-20357f00-8b30-11eb-8847-65a01fb15890.png)
![Screenshot from 2021-03-22 17-00-20](https://user-images.githubusercontent.com/16325331/112068721-2297d900-8b30-11eb-8c10-e9eb5d79cb9e.png)

**Additional debugging information**
- I have a trace file from just now, as well as a trace file from December.  GitHub won't allow me to upload them (unsupported type and too large).  Here's a pointer to the file in GoogleDocs: https://drive.google.com/file/d/1KODZtyOjWKGDmlFvJ2-ZJ3DiAkCvrytZ/view?usp=sharing
- Here's logcat output:
[agi_210322b_logcat_PUBG.txt](https://github.com/google/agi/files/6185780/agi_210322b_logcat_PUBG.txt)

**Comment by ianelliottus** [comment]
Capturing some data from a chat session:

Perhaps related ... Back in December, when I spoke with Cody, he said that when he was creating the PUBG Lite trace (using our ANGLE trace tools), he had to do some manual edits because of another thread that was doing a number of glMakeCurrent calls with an 8x8 image. Thus, it could be the capture library is getting fooled by these glMakeCurrent calls.
From an ANGLE bug I dealt with recently, there is a game that uses one thread (and its own context) to render, and another thread/context to do compute shaders.  Turns out that they were sharing the same Vulkan command buffers.  I wonder if that could be fooling AGI?

**Comment by mark-lunarg** [comment]
Preliminary PR up here:  #777.
