### ISSUE TITLE
AGI does not show Oculus Quest in the devices dropdown

### ISSUE THREAD

**Issue by Acimaz** [google/agi#747]
**Environment information:**
 - AGI version: 1.0.0
 - Host OS: MacOS 11.2.3 Big Sur
 If tracing on Android:
 - Device model: Oculus Quest 1
 - Android Version: I think the quest runs on 7.1.1

**Bug description**
The app simply does not show the Oculus Quest in the devices dropdown, though I can see it via adb devices and debug it with the usual tools like logcat etc.

**Comment by Acimaz** [comment]
Well, I may have been a bit too hyped and oversaw that the tool only unfortunately supports android devices above android version 11

**Comment by pau-baiget** [comment]
Hi @Acimaz , did your problem get resolved then after using Android 11 on your device?

**Comment by Acimaz** [comment]
Hey @pau-baiget, unfortunately, an android update is not possible because it is an Oculus Quest device :)

**Comment by pau-baiget** [comment]
Understood, thanks @Acimaz . I will proceed then to close this issue. Please reopen if necessary, thank you!
