### ISSUE TITLE
Samsung Galaxy S20 5G validation failed

### ISSUE THREAD

**Issue by zhing2006** [google/agi#749]
**Environment information:**
 - AGI version: agi-1.1.0-dev-20210324
 - Host OS: Windows 10
 If tracing on Android:
 - Device model: samsung SM-G9810
 - Android Version: 11

**Bug description**
Samsung Galaxy S20 series is in the supported devices list.
But device support validation failed.

**Reproduction steps**
Run AGI.

**Stacktrace**
N/A

**Screenshots**
![image (1)](https://user-images.githubusercontent.com/5397207/112825217-14acff80-90be-11eb-8fe2-20b52f7c3a92.png)

**Additional debugging information**
N/A

**Comment by zhing2006** [comment]
Succeed.

**Comment by chimppppp** [comment]
> 成功。

how you fix it

**Comment by ttanatb** [comment]
@chimppppp if you're unable to validate your device, please file a separate issue along with the appropriate logs/screenshot, so we can help triage what's going on
