### ISSUE TITLE
Where can I find more implementation detail of Mali and Qualcomm counters?

### ISSUE THREAD

**Issue by ylz-at** [google/agi#753]
As described in,
https://gpuinspector.dev/docs/gpu-counters/arm
https://gpuinspector.dev/docs/gpu-counters/qualcomm

**Comment by hevrard** [comment]
For Mali, see: https://developer.arm.com/ip-products/graphics-and-multimedia/mali-gpus/mali-performance-counters

For Adreno, I'm not aware of a more detailed documentation than what is listed in https://gpuinspector.dev/docs/gpu-counters/qualcomm.

**Comment by hevrard** [comment]
@ylz-at if you manage to find a more detailed documentation for Adreno, don't hesitate to let us know here! Thanks.
