### ISSUE TITLE
Support for OnePlus 8 Pro

### ISSUE THREAD

**Issue by manas-kulkarni** [google/agi#780]
Same chipset as Samsung S20 (Adreno 650) with Android 11

**Comment by jakon2048** [comment]
Will reach out to OnePlus. Thanks.

**Comment by ttanatb** [comment]
Hi all, closing this stale issue.

Support for GPU profiling features require implementation from the device itself, not from additional code in AGI. Moving forward, devices should support GPU profiling features if they have the memory bandwidth to do so, and we've added tests to reduce regressions in subsequent Android releases.
