### ISSUE TITLE
Resource-usage coarsness & Profiling binaries

### ISSUE THREAD

**Issue by singam-sanjay** [google/agi#794]
I have 2 questions,

1. Does agi report the resource usage specific to the app it's profiling or the usage of all apps running on the phone?
2. Can agi profile a binary, for e.g.  that is run through adb shell?

**Comment by stellama0208** [comment]
Hi Singapuram,

Thanks for trying out AGI! And for the questions,

1. May I ask which profiling mode are you using? It could be found at the "Type" field in the "Capture a new trace" config dialog.

- If it's a System Profile trace, and your are looking at the resource usage through "GPU Counters", those counters are global and track all activities. But you could assume the contribution mainly comes from your app, if at the tracing time the GPU activity is mainly about rendering your specific app. If you want an even more precise result, you are always welcome to close other irrelevant apps when tracing. Also, at the "Processes" group, we group some detailed tracks based on process id, you could always locate your app process there, and the tracks beneath it will be specific to the app you are profiling.
- If you opened the experimental flag before and it's a Vulkan/OpenGL trace, the resource usage are specific to the app, like those resources displayed in the "Textures" and "Shaders" tab.

2. I think if you have the binary at hand, you could always adb install the binary and choose that package at the "Application" field in the "Capture a new trace" config dialog. This is the main user journey we currently support. ^_^
