### ISSUE TITLE
Support for any ARM Mali G71 GPU devices?

### ISSUE THREAD

**Issue by armmah** [google/agi#795]
Hello, first of all thanks for the tool, the mobile GPUs in most cases do not provide any actual timings, not to mention the full counters that we are used to on PC and Console platforms that allow to easily pinpoint the bottlnecks. I would have no way of finding out for example that my shader was eating 10 GB/s memory read bandwidth without GPU Inspector, so thanks a lot for the amazing tool and I hope the number of supported devices and the amount of cool features will increase in the future.

Back to the issue - I would like to know if there are any plans to support ANY device with an Arm Mali G71 GPU? I understand that Android 11 is a requirement for GPU Inspector and it seems like Samsung S8 and [Samsung A7](https://www.xda-developers.com/samsung-galaxy-a7-a8-a8-plus-2018-android-11-port-one-ui-3-1/#:~:text=Developer%20ports%20Android%2011%20with,update%20based%20on%20Android%2011.) should be android 11 compatible?

Also, Samsung A20 should get full official android 11 support in August. It is still a couple of months off but if I can hope for support of A20 at august-september that would be unimaginably helpful.

Thanks!

**Comment by jakon2048** [comment]
Thanks for your kind words! 

In Android 11, we're relying on OEMs to grab the necessary patches from Arm or Qualcomm to enable GPU profiling on devices. For cost/marketing reasons, I presume, OEMs are mainly focusing on adding support on their flagship devices. I can follow up with Samsung to see if they have plans to support AGI in their A-series devices. 

However, for reasons that we'll share more later, the device support landscape should be much better post Android 12.

**Comment by armmah** [comment]
I see, so you can't provide any ETAs or promises because its mainly manufacturer's call to make.

It is a shame that a huge market share of devices does not have an appropriate tool for identifying bottlenecks. So I am very interested in this topic and would like to hear any updates that you might have in the future. Please feel free to reach out to me in the future through my email as well - arman.papikyan@ubisoft.com.

Thank you!
