### ISSUE TITLE
Mediatek MT9652 / Arm Mali-G52

### ISSUE THREAD

**Issue by pfk-beta** [google/agi#803]
Hello,

Thanks for great tool, have you asked for support for device mention in the title?

**Comment by jakon2048** [comment]
Hi, yes, we have, but we haven't heard any plans for Mediatek/Arm yet.

**Comment by pfk-beta** [comment]
MT9652

**Comment by jakon2048** [comment]
Which specific device would that be, as in phone model? Sorry! Thanks!

**Comment by pfk-beta** [comment]
It's for TV, e.g. https://www.displayspecifications.com/en/model/20192215

**Comment by jakon2048** [comment]
Thanks. Unfortunately our main focus is mobile devices for now. Perhaps you can try Mali GPU Profiler!
