### ISSUE TITLE
GLES1 game getting wrong image

### ISSUE THREAD

**Issue by ianelliottus** [google/agi#814]
**Environment information:**
 - APK version: versionCode=61603
 - ANGLE version: 89.0.4386.0
 - AGI version: v1.1.0-dev-20210110
 - Host OS: Android 
 If tracing on Android:
 - Device model: Pixel 4 XL (probably doesn't matter)
 - Android Version: 11/RP1A.201005.004/6782484 (probably doesn't matter)

**Bug description**
 - Original description: Replay leads to the overlay layer taking over the whole screen. Maybe an alpha / blending issue?  The drawcall thumbnails show that after the main gameplay rendering is completed, the overlay rendering for the game tutorial instructions is rendered but a huge part of the screen just becomes white, while it should be "transparent" to let the game rendering appear. See screenshots attached.
 - Pau's debugging notes:
   - I attached some screenshot in my previous comment that i thought was correct, but taking a closer look I discovered that replay is not working 100% correctly. The scores above each character are sometimes not rendered correctly.
   - I'm attaching more evidence here. I took a second trace (here) and looked for the drawcalls that are rendering the scores correctly and incorrectly (attached screenshots with expanded command trees). I took a few traces and I can always reproduce the same pattern: first character gets the upper score rendered correctly and then all the rest get it wrong in several ways. See attached dumped screenshot from AGI vs actual screenshot.
   - It feels like AGI is not keeping the internal state consistent after rendering the score panel for the lower-left (first) character of the game.

**Reproduction steps**
More details will be communicated privately ...

**Screenshots**
From Pau
![first_character_good](https://user-images.githubusercontent.com/16325331/121075467-d6594e00-c79a-11eb-9cd2-b8a8fc3c8741.png)
![second_character_wrong](https://user-images.githubusercontent.com/16325331/121075483-db1e0200-c79a-11eb-93af-a573350b4782.png)
![screenshot_from_device-summoners-war](https://user-images.githubusercontent.com/16325331/121075512-dfe2b600-c79a-11eb-83a5-8ee3b4e2d641.png)
![screenshot_agi_vkQueuePresent](https://user-images.githubusercontent.com/16325331/121075522-e2451000-c79a-11eb-8053-ab3657a855ae.png)

**Additional debugging information**
- Please attach the generated _gapis.log_ and _gapic.log_ files you will find in the temp folder (e.g. /tmp/ on linux).
- If using Android: Please attach a full logcat dump (```adb logcat -d > logcat-full.txt```) that contains logs since AGI was started.

**Comment by ianelliottus** [comment]
I was thinking that @mark-lunarg would take this one, but please work it out between Mark and Mike

**Comment by ianelliottus** [comment]
Note: This replaces internal issue b/177837689, and is mirrored by internal issue b/190429069

**Comment by mark-lunarg** [comment]
There appears to be an additional ANGLE issue that shows up on a **Pixel 5** (screenshot below -- none of the seven characters is rendered correctly).  Verified with Mike that his **Pixel 4** repros exactly as Pau's does.  This looks like it could also be blending related, but we believe it is _probably_ distinct from the issue that shows up in the traces.  

![Screenshot_20210608-142112](https://user-images.githubusercontent.com/7252958/121254146-2998d280-c867-11eb-9b8f-8560a76891a3.png)

**Comment by ianelliottus** [comment]
Interesting.  Let me ask some questions to clarify the Pixel 5 behavior:

- Like the original bug, is the problem only with playback of the trace?  That is,
  - Is the game is rendered correctly when played with ANGLE (no AGI)?
  - Does the game render correctly when played while doing an AGI frame capture?

Either way, please try to debug the Pixel 5 issue further.  Thanks Mark!

**Comment by mark-lunarg** [comment]
The Pixel5-specific issues are definitely ANGLE -- AGI is not involved.
