### ISSUE TITLE
Support OnePlus Pro 9

### ISSUE THREAD

**Issue by m0ppers** [google/agi#830]
Android 11
Adreno 660

Would be great to have support for it.

**Comment by jakon2048** [comment]
I've just heard from Oppo that OnePlus 9R has received support. Let me follow up on OnePlus Pro 9.

**Comment by ttanatb** [comment]
Hi all, closing this stale issue.

Support for GPU profiling features require implementation from the device itself, not from additional code in AGI. Moving forward, devices should support GPU profiling features if they have the memory bandwidth to do so, and we've added tests to reduce regressions in subsequent Android releases.
