### ISSUE TITLE
Redmi K40 When can it be supported? ?

### ISSUE THREAD

**Issue by zeng-zeng367** [google/agi#835]

**Comment by jakon2048** [comment]
Will reach out to Xiaomi to see.

**Comment by zeng-zeng367** [comment]
Is it going well?

**Comment by jakon2048** [comment]
Hi, we've reached out to Xiaomi but haven't heard back yet. Will follow up again.

**Comment by ttanatb** [comment]
Hi all, closing this stale issue.

Support for GPU profiling features require implementation from the device itself, not from additional code in AGI. Moving forward, devices should support GPU profiling features if they have the memory bandwidth to do so, and we've added tests to reduce regressions in subsequent Android releases.
