### ISSUE TITLE
How can I build bazel  project

### ISSUE THREAD

**Issue by ZhangYi19860922** [google/agi#847]
**Environment information:**
 - AGI version: latest
 - Host OS: Windows10
 If tracing on Android:
 - Device model:
 - Android Version:

**Bug description**
when I start to build AGI project, the bazel system reports an error, pointing to the fetch of repository named "bazel_gazelle". How can I download the dependent files by myself and bypass the auto-load build chains.

**Reproduction steps**
1. enter the AGI project home
2. make cmd : "bazel build pkg"

**Stacktrace**
Please paste a stacktrace here if it's available.

**Screenshots**

**Additional debugging information**
- Please attach the generated _gapis.log_ and _gapic.log_ files you will find in the temp folder (e.g. /tmp/ on linux).
- If using Android: Please attach a full logcat dump (```adb logcat -d > logcat-full.txt```) that contains logs since AGI was started.

ERROR: An error occurred during the fetch of repository 'bazel_gazelle':
   java.io.IOException: Error downloading [https://codeload.github.com/bazelbuild/bazel-gazelle/zip/9b9f0226e01d10a70cbf268f9967cb715c8ff067] to D:/users/80325561/_bazel_80325561/rog7hrpg/external/bazel_gazelle/9b9f0226e01d10a70cbf268f9967cb715c8ff067.zip: PKIX path building 
failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
ERROR: no such package '@bazel_gazelle//': java.io.IOException: Error downloading [https://codeload.github.com/bazelbuild/bazel-gazelle/zip/9b9f0226e01d10a70cbf268f9967cb715c8ff067] to D:/users/80325561/_bazel_80325561/rog7hrpg/external/bazel_gazelle/9b9f0226e01d10a70cbf268f9
967cb715c8ff067.zip: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
ERROR: no such package '@bazel_gazelle//': java.io.IOException: Error downloading [https://codeload.github.com/bazelbuild/bazel-gazelle/zip/9b9f0226e01d10a70cbf268f9967cb715c8ff067] to D:/users/80325561/_bazel_80325561/rog7hrpg/external/bazel_gazelle/9b9f0226e01d10a70cbf268f9
967cb715c8ff067.zip: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
INFO: Elapsed time: 14.869s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (0 packages loaded)
FAILED: Build did NOT complete successfully (0 packages loaded)

**Comment by matled** [comment]
The relevant error is:
```
sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
```

This appears to indicates that the certificate of codeload.github.com could not be validated for the resource https://codeload.github.com/bazelbuild/bazel-gazelle/zip/9b9f0226e01d10a70cbf268f9967cb715c8ff067

When I connect to the server, this is what I get:
```
% openssl s_client -connect codeload.github.com:443
CONNECTED(00000003)                                                                                              
depth=2 C = US, O = DigiCert Inc, OU = www.digicert.com, CN = DigiCert High Assurance EV Root CA
verify return:1                                                                                                  
depth=1 C = US, O = "DigiCert, Inc.", CN = DigiCert High Assurance TLS Hybrid ECC SHA256 2020 CA1
verify return:1                                                                                                  
depth=0 C = US, ST = California, L = San Francisco, O = "GitHub, Inc.", CN = *.github.com
verify return:1                                  
```

I.e. the certificate is signed by DigiCert (some responses to the error indicate that this happens for self-signed, but I think this is only one possible reason for the failure).

I'm not familiar where bazel / Java searches for the certificates or how they are updated.

I'd recommend trying to determine if this is an issue exclusive to bazel, or if this happens for other applications/tools accessing the resource, too. This may help to pinpoint and resolve the issue. For example:
1. Try to open the resource in (different) browsers.
2. Perform a web request in PowerShell: `Invoke-WebRequest -OutFile resource.zip -Uri https://codeload.github.com/bazelbuild/bazel-gazelle/zip/9b9f0226e01d10a70cbf268f9967cb715c8ff067`

As a workaround, you may be able to place the resource in the desired location for bazel (see the path starting with `D:/users` in the error message).

**Comment by ZhangYi19860922** [comment]
Thanks. This problem has been solved when I download the dependent resources manually. I have changed the URL to a local path with .zip suffix, like:
url = "https://codeload.github.com/{organization}/{project}/zip/{commit}"  ———>>  url = "http://localURL /{organization}/{project}/zip/{commit}.zip".

But here is another new while building, the build log shows below. Are there any tools I forgot to install or prepare ?

bazel : Starting local Bazel server and connecting to it...
所¨´在¨²位?置? 行D:1 字Á?符¤?: 1
+ bazel build pkg
+ ~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (Starting local ...ecting to it...:String) [], RemoteException
    + FullyQualifiedErrorId : NativeCommandError
Loading:
Loading: 0 packages loaded
Analyzing: target //:pkg (1 packages loaded, 0 targets configured)
Analyzing: target //:pkg (24 packages loaded, 32 targets configured)
Analyzing: target //:pkg (24 packages loaded, 32 targets configured)
Analyzing: target //:pkg (24 packages loaded, 32 targets configured)
Analyzing: target //:pkg (24 packages loaded, 32 targets configured)
INFO: Call stack for the definition of repository 'local_config_cc' which is a _configure_toolchain (rule definition at D:/users/80325561/_bazel_80325561/rog7hrpg/external/gapid/tools/build/cc_toolchain.bzl:94:24):
- D:/users/80325561/_bazel_80325561/rog7hrpg/external/gapid/tools/build/cc_toolchain.bzl:113:3
- D:/users/80325561/_bazel_80325561/rog7hrpg/external/gapid/tools/build/workspace.bzl:353:9
- E:/projects/agi-master/WORKSPACE:22:1
Analyzing: target //:pkg (24 packages loaded, 32 targets configured)
ERROR: An error occurred during the fetch of repository 'local_config_cc':
   Traceback (most recent call last):
     File "D:/users/80325561/_bazel_80325561/rog7hrpg/external/gapid/tools/build/cc_toolchain.bzl", line 88
         _configure_windows_toolchain(<1 more arguments>)
     File "D:/users/80325561/_bazel_80325561/rog7hrpg/external/gapid/tools/build/cc_toolchain.bzl", line 68, in _configure_windows_toolchain
         _compile_wrapper(repository_ctx, <2 more arguments>)
     File "D:/users/80325561/_bazel_80325561/rog7hrpg/external/gapid/tools/build/cc_toolchain.bzl", line 54, in _compile_wrapper
         fail(<1 more arguments>)
Failed to build gcc_wrapper: 1
D:/users/80325561/_bazel_80325561/rog7hrpg/external/local_config_cc/file_collector.cpp:17:10: fatal error: direct.h: No such file or directory
   17 | #include <direct.h>
      |          ^~~~~~~~~~
compilation terminated.
INFO: Call stack for the definition of repository 'go_sdk' which is a _go_download_sdk (rule definition at D:/users/80325561/_bazel_80325561/rog7hrpg/external/io_bazel_rules_go/go/private/sdk.bzl:79:20):
- D:/users/80325561/_bazel_80325561/rog7hrpg/external/io_bazel_rules_go/go/private/sdk.bzl:92:5
- D:/users/80325561/_bazel_80325561/rog7hrpg/external/io_bazel_rules_go/go/private/sdk.bzl:260:13
- E:/projects/agi-master/WORKSPACE:34:1
ERROR: no such package ***@***.***_config_cc//': Traceback (most recent call last):
     File "D:/users/80325561/_bazel_80325561/rog7hrpg/external/gapid/tools/build/cc_toolchain.bzl", line 88
         _configure_windows_toolchain(<1 more arguments>)
     File "D:/users/80325561/_bazel_80325561/rog7hrpg/external/gapid/tools/build/cc_toolchain.bzl", line 68, in _configure_windows_toolchain
         _compile_wrapper(repository_ctx, <2 more arguments>)
     File "D:/users/80325561/_bazel_80325561/rog7hrpg/external/gapid/tools/build/cc_toolchain.bzl", line 54, in _compile_wrapper
         fail(<1 more arguments>)
Failed to build gcc_wrapper: 1
D:/users/80325561/_bazel_80325561/rog7hrpg/external/local_config_cc/file_collector.cpp:17:10: fatal error: direct.h: No such file or directory
   17 | #include <direct.h>
      |          ^~~~~~~~~~
compilation terminated.
ERROR: Analysis of target '//:pkg' failed; build aborted: no such package ***@***.***_config_cc//': Traceback (most recent call last):
     File "D:/users/80325561/_bazel_80325561/rog7hrpg/external/gapid/tools/build/cc_toolchain.bzl", line 88
         _configure_windows_toolchain(<1 more arguments>)
     File "D:/users/80325561/_bazel_80325561/rog7hrpg/external/gapid/tools/build/cc_toolchain.bzl", line 68, in _configure_windows_toolchain
         _compile_wrapper(repository_ctx, <2 more arguments>)
     File "D:/users/80325561/_bazel_80325561/rog7hrpg/external/gapid/tools/build/cc_toolchain.bzl", line 54, in _compile_wrapper
         fail(<1 more arguments>)
Failed to build gcc_wrapper: 1
D:/users/80325561/_bazel_80325561/rog7hrpg/external/local_config_cc/file_collector.cpp:17:10: fatal error: direct.h: No such file or directory
   17 | #include <direct.h>
      |          ^~~~~~~~~~
compilation terminated.
INFO: Elapsed time: 11.956s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (24 packages loaded, 32 targets configured)
FAILED: Build did NOT complete successfully (24 packages loaded, 32 targets configured)

发件人: Matthias Lederhofer ***@***.***>
发送时间: 2021年6月30日 18:54
收件人: google/agi ***@***.***>
抄送: 张一(henry) ***@***.***>; Author ***@***.***>
主题: Re: [google/agi] How can I build bazel project (#847)


The relevant error is:

sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target

This appears to indicates that the certificate of codeload.github.com could not be validated for the resource https://codeload.github.com/bazelbuild/bazel-gazelle/zip/9b9f0226e01d10a70cbf268f9967cb715c8ff067<https://apc01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fcodeload.github.com%2Fbazelbuild%2Fbazel-gazelle%2Fzip%2F9b9f0226e01d10a70cbf268f9967cb715c8ff067&data=04%7C01%7Czhangyi123%40oppo.com%7Cf5abfbeba3da45938daa08d93bb56f3a%7Cf1905eb1c35341c5951662b4a54b5ee6%7C0%7C0%7C637606472710037080%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=psWbB6zvLosSeD%2FtjeuVsjCPaTLziTNZzpxOz4egLCI%3D&reserved=0>

When I connect to the server, this is what I get:

% openssl s_client -connect codeload.github.com:443

CONNECTED(00000003)

depth=2 C = US, O = DigiCert Inc, OU = www.digicert.com, CN = DigiCert High Assurance EV Root CA

verify return:1

depth=1 C = US, O = "DigiCert, Inc.", CN = DigiCert High Assurance TLS Hybrid ECC SHA256 2020 CA1

verify return:1

depth=0 C = US, ST = California, L = San Francisco, O = "GitHub, Inc.", CN = *.github.com

verify return:1

I.e. the certificate is signed by DigiCert (some responses to the error indicate that this happens for self-signed, but I think this is only one possible reason for the failure).

I'm not familiar where bazel / Java searches for the certificates or how they are updated.

I'd recommend trying to determine if this is an issue exclusive to bazel, or if this happens for other applications/tools accessing the resource, too. This may help to pinpoint and resolve the issue. For example:

  1.  Try to open the resource in (different) browsers.
  2.  Perform a web request in PowerShell: Invoke-WebRequest -OutFile resource.zip -Uri https://codeload.github.com/bazelbuild/bazel-gazelle/zip/9b9f0226e01d10a70cbf268f9967cb715c8ff067

As a workaround, you may be able to place the resource in the desired location for bazel (see the path starting with D:/users in the error message).

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub<https://apc01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fgoogle%2Fagi%2Fissues%2F847%23issuecomment-871299606&data=04%7C01%7Czhangyi123%40oppo.com%7Cf5abfbeba3da45938daa08d93bb56f3a%7Cf1905eb1c35341c5951662b4a54b5ee6%7C0%7C0%7C637606472710047076%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=lPU9zxGsM9KzOEuHhDHTK%2BmeOGlofh4F51KVKRcJIso%3D&reserved=0>, or unsubscribe<https://apc01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAUVO3TFH3UWZJSVB3S6PFYTTVLZWFANCNFSM47RNHRMQ&data=04%7C01%7Czhangyi123%40oppo.com%7Cf5abfbeba3da45938daa08d93bb56f3a%7Cf1905eb1c35341c5951662b4a54b5ee6%7C0%7C0%7C637606472710057068%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=l1fqgxaJZgsxsg4FdnMDZImr7XxZHq1ViojH%2Fxa%2FKnE%3D&reserved=0>.

________________________________
OPPO

本电子邮件及其附件含有OPPO公司的保密信息，仅限于邮件指明的收件人使用（包含个人及群组）。禁止任何人在未经授权的情况下以任何形式使用。如果您错收了本邮件，请立即以电子邮件通知发件人并删除本邮件及其附件。

This e-mail and its attachments contain confidential information from OPPO, which is intended only for the person or entity whose address is listed above. Any use of the information contained herein in any way (including, but not limited to, total or partial disclosure, reproduction, or dissemination) by persons other than the intended recipient(s) is prohibited. If you receive this e-mail in error, please notify the sender by phone or email immediately and delete it!

**Comment by hevrard** [comment]
It looks like your C++ compiler cannot find the `direct.h` header.

Before diving into this, let's take a step back: did you follow the build instructions for windows, especially did you install the recommended gcc version, etc?
https://github.com/google/agi/blob/master/BUILDING.md#windows

This is to make sure we are on the same page regarding versions of requirements, etc.
