### ISSUE TITLE
Setup Golang development - trouble getting it to work with VSCode

### ISSUE THREAD

**Issue by AndyCGYan** [google/agi#876]
**Environment information:**
 - AGI version: (local build from master)
 - Host OS: Ubuntu 18.04 LTS

**Bug description**
Following the "Setup Golang development" section in DEVDOC, I'm able to complete a build and run gofuse to create links, but viewing in VSCode doesn't really work. It asked me to install a bunch of analysis tools (gopls, etc.), but after installing them, gopls complains:
```
Error loading workspace: gopls requires a module at the root of your workspace.
You can work with multiple modules by opening each one as a workspace folder.
Improvements to this workflow will be coming soon, and you can learn more here:
https://github.com/golang/tools/blob/master/gopls/doc/workspace.md.
```
One way around this specific error is adding this to settings:
```
"gopls": {
    "experimentalWorkspaceModule": true
}
```
However, doing so here results in another error:
```
Error loading workspace: found module "xxx" twice in the workspace
```

**Reproduction steps**
Following the "Setup Golang development" section in DEVDOC.

**Comment by AndyCGYan** [comment]
I've worked around the initial issue by adding a dedicated folder to `GOPATH` for `bin`/`pkg`, therefore separating them from the workspace.

Now it fails on something else - most local Go imports fail, with similar error to this:
```
could not import github.com/google/gapid/core/app (cannot find package "github.com/google/gapid/core/app" in any of 
	/usr/local/go/src/github.com/google/gapid/core/app (from $GOROOT)
	/home/user/GOPKG/src/github.com/google/gapid/core/app (from $GOPATH)
	/home/user/agi-gofuse/src/github.com/google/gapid/core/app (from $GOPATH))
```
...but I'm certain that the paths exist and are populated:
```
~$ ls /home/user/agi-gofuse/src/github.com/google/gapid/core/app 
analytics  BUILD.bazel            doc.go    layout      profile.go  verbs.go
atexit.go  cleanup.go             flags     linker      run.go
auth       crash                  flags.go  log.go      stack.go
benchmark  default_version.go.in  help.go   oncrash.go  status
```

**Comment by yalcinmelihyasin** [comment]
Have you build the pkg after the go-fuse again? You need to build the package again so that files that go-fuse link are at the place that they should be.

**Comment by AndyCGYan** [comment]
> Have you build the pkg after the go-fuse again? You need to build the package again so that files that go-fuse link are at the place that they should be.

No change after doing so.

In the meantime, I found out that setting `GO111MODULE` to off gets it mostly going - the majority of GAPID is written before Go 1.11 and the introduction of Go modules, so I guess that makes sense. None of these above are documented in DEVDOC though - either there's a "correct" solution out there (in which case please point out), or perhaps it (and BUILDING too) could use some review and update?

Also, by "mostly going", I mean there are still a good number (3K+) of problems reported by VSCode, mostly `not declared by package C` and `undeclared name`.

**Comment by yalcinmelihyasin** [comment]
I see. Yes unfortunately we haven't migrated to go modules yet. 

I think that the problems that reported are can be omitted as they don't prevent the general usage and we have other tools for linting & style.

**Comment by yalcinmelihyasin** [comment]
We use the VScode for mainly jumping around the code. Does that feature works for you?

**Comment by AndyCGYan** [comment]
> Yes unfortunately we haven't migrated to go modules yet.

Thanks for confirming.

> We use the VScode for mainly jumping around the code. Does that feature works for you?

That's also what I'm after. Again, mostly works - aside from what's caused by the above problems, in rare occasions, even within a file that reported no problems, I get no references or jump to the wrong file.

**Comment by yalcinmelihyasin** [comment]
Can you please provide which files that error occurs? Is it random or consistent in certain files. 

Sometimes I do observe that Go Plugin stops working and I simply restart VSCode. If they are happening in certain files, I can take a look at them.

**Comment by AndyCGYan** [comment]
The problem count is a consistent ~3.4K ever since I disabled `GO111MODULE`.

- **Many of them occur outside of the main gapid source path, i.e. `src/github.com/google/gapid`.** Still, I don't think they should happen, if I've been following DEVDOC.
- ~1.8K of which are "not declared by package C", e.g. all `C.*` references in `core/archive/archive.go`. This is accompanied by:

`go list failed to return CompiledGoFiles. This may indicate failure to perform cgo processing; try building at the command line. See https://golang.org/issue/38990.`

- ~1.2K of which are "undeclared name", e.g. `Builtin_*` in `gapil/bapi/{encode,decode}.go`
- 100+ of which are broken imports, e.g. all external imports in `src/github.com/google/go-github/example/appengine/app.go`.

**Comment by thalesfsp** [comment]
How to disable this annoying message?

**Comment by yalcinmelihyasin** [comment]
This issue is more of an issue of VSCode rather than AGI's itself.
