### ISSUE TITLE
OPPO Find X3 support validation failed

### ISSUE THREAD

**Issue by 1860Sonic** [google/agi#884]
**Environment information:**
 - AGI version:2021-2.0.0:aad09f92ea8e608b11001aae1f93af3cc1101096
 - Host OS: macOs
 If tracing on Android:
 - Device model:OPPO PEDMOO 
 - Android Version: 11 API 30
 - Qualcomm Adreno(TM) 650 - dac23338

device support validation failed

caption a new trace

![image](https://user-images.githubusercontent.com/11907187/126112331-f9f64bbb-14bf-40c0-82ce-86a019866027.png)

**Comment by arfanty** [comment]
Exactly the same situation. Tried to use "gapit validate_gpu_profile" and I got this:

11:03:10.017 I: <gapit> Exec: D:\agi\gapis.exe --enable-local-files --idle-timeout 1m --log-level Info --log-style brief --gapis-auth-token aVKsqXX6
11:03:10.409 I: <gapis.exe> 11:03:10.409 I: <gapis> Adding new device
11:03:10.409 I: <gapis.exe> 11:03:10.409 I: <gapis> New scheduler for device: 45b46da602110705288b5f4e9d7c385f336f1414
11:03:10.409 I: <gapis.exe> 11:03:10.409 I: <gapis> New trace scheduler for device: 45b46da602110705288b5f4e9d7c385f336f1414 GIH-D-20862
11:03:10.416 I: <gapis.exe>
11:03:10.416 I: <gapis.exe> Bound on port '58917'
11:03:10.416 I: <gapis.exe> 11:03:10.416 I: <gapis> Starting grpc server
19:03:11.053 I: [Try ABI: arm64-v8a⇒gapidapk.EnsureInstalled] <gapis> Examining gapid.apk on host...
19:03:11.058 I: [Try ABI: arm64-v8a⇒gapidapk.EnsureInstalled] <gapis> Looking for gapid.apk...
19:03:11.290 I: [Try ABI: arm64-v8a⇒gapidapk.EnsureInstalled] <gapis> Found gapid package...
19:03:11.597 I: <gapis> No developer driver found, attempting to use GPU profiling libraries in system image.
19:03:12.641 I: <gapis> [launch producer] I: Trying libgpudataproducer.so
19:03:12.641 I: <gapis> [launch producer] I: Calling start at 0x7a3fe74e08
19:03:12.644 I: <gapis> [launch producer] QPerfettoCountersDataPro QProfilerInterface: Initializing (v2020.10, built May 22 2021@22:45:36)...
19:03:12.677 I: <gapis> [launch producer] QPerfettoCountersDataPro gpu.counters: Starting tracing thread
19:03:12.681 I: <gapis> [launch producer] perfetto.cc:39641        Producer connected
19:03:12.771 I: <gapis> [launch producer] QPerfettoCountersDataPro Start counter trace returned 0
19:03:13.641 I: [startDevInfoService] <gapis> Attempt to start service: com.google.android.gapid.DeviceInfoService
19:03:16.294 I: <gapis> Adding new device
19:03:16.294 I: <gapis> Adding new device
19:03:16.294 I: <gapis> New scheduler for device: 3d6065fb4c24b0a1e116e64347adea50c6ea5771
19:03:16.294 I: <gapis> New trace scheduler for device: 3d6065fb4c24b0a1e116e64347adea50c6ea5771 OPPO PEEM00
-- Device 0: 45b46da602110705288b5f4e9d7c385f336f1414 --
Device is validated.
-- Device 1: 3d6065fb4c24b0a1e116e64347adea50c6ea5771 --
19:03:16.829 I: [start⇒ValidateDevice] <gapis> No developer driver found, attempting to use GPU profiling libraries in system image.
19:03:17.279 I: [start⇒ValidateDevice] <gapis> Unlocking device screen
19:03:17.931 I: <gapis> [launch producer] Exit.
19:03:17.931 E: <gapis> [EnsurePerfettoProducerLaunched] error: exit status 143
19:03:18.191 I: [start⇒ValidateDevice] <gapis> [launch producer] I: Trying libgpudataproducer.so
19:03:18.196 I: [start⇒ValidateDevice] <gapis> [launch producer] I: Calling start at 0x75bdfb4e08
19:03:18.196 I: [start⇒ValidateDevice] <gapis> [launch producer] QPerfettoCountersDataPro QProfilerInterface: Initializing (v2020.10, built May 22 2021@22:45:36)...
19:03:18.206 I: [start⇒ValidateDevice] <gapis> [launch producer] QPerfettoCountersDataPro gpu.counters: Starting tracing thread
19:03:18.207 I: [start⇒ValidateDevice] <gapis> [launch producer] perfetto.cc:39641        Producer connected
19:03:18.303 I: [start⇒ValidateDevice] <gapis> [launch producer] QPerfettoCountersDataPro Start counter trace returned 0
19:03:21.531 I: [start⇒ValidateDevice] <gapis> [launch producer] perfetto.cc:40011        Setting up data source 43 gpu.counters
19:03:21.531 I: [start⇒ValidateDevice] <gapis> [launch producer] QPerfettoCountersDataPro gpu.counters: OnSetup called, name: gpu.counters, trace_duration_ms: 7000, counter_period_ms: 50, tracing_session_id: 20, session: 0xb4000075ba422580
19:03:21.531 I: [start⇒ValidateDevice] <gapis> [launch producer] perfetto.cc:40078        Starting data source 43
19:03:21.531 I: [start⇒ValidateDevice] <gapis> [launch producer] QPerfettoCountersDataPro gpu.counters: OnStart called, session: 0xb4000075ba422580
19:03:28.533 I: [start⇒ValidateDevice] <gapis> [launch producer] perfetto.cc:40095        Stopping data source 43
19:03:28.764 I: [start⇒ValidateDevice] <gapis> [launch producer] QPerfettoCountersDataPro gpu.counters: OnStop called, session: 0xb4000075ba422580
19:03:28.764 I: [start⇒ValidateDevice] <gapis> [launch producer] perfetto.cc:40128        Ending async stop of data source 43
19:03:28.800 I: [ValidateDevice] <gapis> Perfetto trace size 79971 bytes
Failed to validate device
   Cause: Internal error: Check failed for counter: {31 Textures / Fragment 0x7ff7866c9630}
19:03:29.367 W: [start⇒ValidateDevice] <gapis> Killing C:\Development\android-sdk-manager\platform-tools\adb.exe (context cancelled)
19:03:29.367 I: [start⇒ValidateDevice] <gapis> [launch producer] Exit.
19:03:29.367 E: [start⇒ValidateDevice] <gapis> [EnsurePerfettoProducerLaunched] error: context canceled
11:03:29.367 E: <gapit> Main failed
Error: Some device failed validation
11:03:29.367 W: <gapit> Killing D:\agi\gapis.exe (context cancelled)

**Comment by jakon2048** [comment]
Let me reach out to Oppo on this. Thanks for reporting.

**Comment by jakon2048** [comment]
Arfanty, could you please provide the build number of your device?

(Settings->About phone->version->Build number)

**Comment by rssqian** [comment]
Build Number: PEEM00_11_A_26

**Comment by Luftschloss** [comment]
Device support validation failed
AGI Version：2021-2.0.0:aad09f92ea8e608b11001aae1f93af3cc1101096
Host OS：Windows 10
Device：OPPO Find X3（Android 11 API 30，Adreno(TM) 650）
Build Number: PEEM00_11_A.24

**Comment by jakon2048** [comment]
Hi everyone, we've contacted Oppo and they're looking into it.

**Comment by jakon2048** [comment]
Hi all, Oppo mentioned the following two things to get AGI working:

1. Update the device to build PEDM00_11_A.28
2. Go to developer settings, and disable permission monitoring.

Thanks!
