### ISSUE TITLE
Samsung Galaxy S10 support validation failed

### ISSUE THREAD

**Issue by VladislavKhudziakov** [google/agi#885]
Environment information:

AGI version: 2021-2.0.0:aad09f92ea8e608b11001aae1f93af3cc1101096
Host OS: macOs
Device model: Samsung Galaxy S10
Android: Version 10 API 29 - ARM - Mali-G76

Error: device support validation failed

Steps to reproduce:
Try to caption new frame. 
<img width="656" alt="Screenshot 2021-07-19 at 16 37 43" src="https://user-images.githubusercontent.com/43790133/126169143-f034e388-49ff-4ef3-9b91-bbd2d3faf180.png">

**Comment by pmuetschard** [comment]
You need to update your device to Android 11 for AGI support. Take a look at our supported devices page here: https://gpuinspector.dev/docs/devices
