### ISSUE TITLE
Please add a resource "size" column for sorting to textures and geomegry

### ISSUE THREAD

**Issue by alecazam** [google/agi#902]
**Environment information:**
 - AGI version: 2021-2.0.0:aad09f92ea8e608b11001aae1f93af3cc1101096
 - Host OS: macOS 11.4
 If tracing on Android:
 - Device model: Galaxy10se w/Mali-G76 gpu
 - Android Version: 11

**Bug description**
The texture view doesn't have a "size" column, and there's no good way to sort the largest textures when you have different compressions.   There needs to be a computed size.  

![image](https://user-images.githubusercontent.com/3750359/129461421-cc4fb929-5386-4c0a-898b-1dce79057130.png)

Also replicate this info at the top of the "Texture" panel since the columns are compacted so small that you can't read the format.  Here the columns have collapsed back to 3 characters, and I can't read the format anymore.
![image](https://user-images.githubusercontent.com/3750359/129461441-5485a3e3-92a3-4daf-b3b5-52faa01b52e9.png)

**Reproduction steps**
1. Look at a frame capture
2. View the "Textures" panel
3. Now try to find the textures that are largest in size.  (Same could be said for geometry/buffers).

**Stacktrace**
Not applicable

**Screenshots**
See above.

**Additional debugging information**
None

**Comment by alecazam** [comment]
I also filed a bug about not getting labels or debug_marker scopes around our draw commands.  That also makes interpreting this list very difficult with 2000 textures.

**Comment by pmuetschard** [comment]
Thank you for the feedback. Yes, showing the size is an improvement we are aware of and your feedback can help us prioritize this.

The columns in the table are resizable, but I do agree the automatic sizing is currently not good and can even be annoying.

**Comment by ttanatb** [comment]
Table columnns should be auto-resized on load to the size of its content now, and a column for the computed size has been added.

**Comment by alecazam** [comment]
Thanks for adding this!  Looking forward to using the size field.
