### ISSUE TITLE
Need clear indicators of vsync and framebuffer output.

### ISSUE THREAD

**Issue by alecazam** [google/agi#915]
**Environment information:**
 - AGI version: 2021-2.0.0:aad09f92ea8e608b11001aae1f93af3cc1101096
 - Host OS: macOS 11.4
 If tracing on Android:
 - Device model: Galaxy 10se (Mali G76)
 - Android Version: 11

**Bug description**
"System Profile" needs to clearly indicate the vsync deadline across all captures, and when it is missed.  If viewing an Xcode Instruments capture, this is one of the main elements that is useful since all vertex/fragment work must complete prior.  Need similar ticks/markers in AGI captures.

**Reproduction steps**
Do a "System Profile" and then try to locate the vsync deadline in the sea of data presented.

**Stacktrace**
Not applicable

**Screenshots**
None

**Additional debugging information**
None

**Comment by pmuetschard** [comment]
Thank you for the feedback. For VSync: in the trace dialog, ensure you have the "Frame Lifecycle" option enabled. This will cause SurfaceFlinger to issue events from the buffer queue. These events are then processed and shown the the frame lifecycle tracks. There you can see how the buffers flow through your application and make it obvious if a sync was missed. You can also enable VSync overlay by pressing the 'V' key. Once enabled, AGI will keep it enabled for other traces.
