### ISSUE TITLE
The AGI replay continuous frame-capture and replay

### ISSUE THREAD

**Issue by ZhangYi19860922** [google/agi#916]
Hi, 
   AGI teams. I'm going to learn about the AGI source code on android platform, is there any architectural doc about the communications between AGI modules . The project contains multiple languages, how should I debug them all together? If I want to develop a new feature ---- continuous multi-frames replay, where should I start.
  Thanks.

**Comment by pmuetschard** [comment]
Documentation is pretty sparse, I'm afraid. We have the User documentation https://developer.android.com/agi, the documentation generated from the Go code https://pkg.go.dev/github.com/google/agi and some README files throughout the code.
