### ISSUE TITLE
Starting an App for Frame Tracing crashes app on its splashscreen

### ISSUE THREAD

**Issue by ssnd292** [google/agi#922]
**Environment information:**
 - AGI version: 2021-2.1.0:dev-20210902-70e2408ae5db5817ea32f633f0ba51c7a57edd87
 - Host OS: Windows 10
 If tracing on Android:
 - Device model: Pixel 4A
 - Android Version: Android 11 Build RQA3A.210805.001.A1
 - App Rendering API: OpenGLES3

**Bug description**
AGI was recommended to us by Francesco Carucci for profiling our game and seeing where we are loosing performance.
However, our game consistently crashes when we try to run a Frame Trace.

I suspect it is connected to ANGLE as the app will also crash regardless if we start it via AGI or not. But the app will work fine if we uninstall ANGLE (however, we can not do a Frame Trace without)

Logs:
[AGI_Crash.log](https://github.com/google/agi/files/7127068/AGI_Crash.log)
[gapic.log](https://github.com/google/agi/files/7127069/gapic.log)
[gapis.log](https://github.com/google/agi/files/7127070/gapis.log)
[logcat.txt](https://github.com/google/agi/files/7127071/logcat.txt)

**Comment by ianelliottus** [comment]
We tried to reproduce this, but are not sure where to find this game: com.stratospheregames.nimbusgbx

Is it available on the PlayStore?  If not, is there a way you can make it available to us?

**Comment by mark-lunarg** [comment]
@ssnd292, is there an update please?

**Comment by ssnd292** [comment]
Sorry for answering so late.
The crash was probably resolved by some of the recent dev versions and inherintly different ANGLE versions.

We're still not able to get a Frame Profile but that should go into a different ticket.
