### ISSUE TITLE
Support for Essential Phone

### ISSUE THREAD

**Issue by liuyibox** [google/agi#933]
**Environment information:**
 - AGI version: AGI 2021-2.0.0
 - Host OS: Linux
 If tracing on Android:
 - Device model: PH-1
 - Android Version: 9

**Bug description**
I am using the Essential Phone whose manufacturing has been stopped. However, this phone contains the Qualcomm Adreno 540 with OpenGL ES 3.2. Current agi does not support. 

Is that possible that I modify the AGI source code to support 540 GPU? Thanks.

**Comment by ttanatb** [comment]
Hi all, closing this stale issue.

Support for GPU profiling features require implementation from the device itself, not from additional code in AGI. Moving forward, devices should support GPU profiling features if they have the memory bandwidth to do so, and we've added tests to reduce regressions in subsequent Android releases.
