### ISSUE TITLE
Samsung Galaxy S21 support validation failed

### ISSUE THREAD

**Issue by ffk0716** [google/agi#934]
Environment information:

AGI version: Version agi-2.1.0-dev-20210916-linux
Host OS: Linux
If tracing on Android:
Device model: Samsung Galaxy S21 Exynos 2100
Android Version: 11
GPU: Mali-G78 GPU
Bug description
device support validation failed

Steps to reproduce:
Take a new trace
![unnamed](https://user-images.githubusercontent.com/9611630/134858997-9bc9290b-962b-4b44-8256-a6b9e5bbc460.png)

**Comment by pau-baiget** [comment]
Thanks for reporting this issue. I've been trying the [latest dev release](https://github.com/google/agi-dev-releases/releases/tag/v2.1.0-dev-20210924) with a Galaxy S21 and I've been able to pass validation 100% of the times. I'm however using a slightly different version of the S21 (SM-G998B, which is the Ultra version). AFAIK the two models should have no difference in terms of driver version, however let's verify this.

Can you please run the following commands and report the results here?
Build fingerprint (in my case it is ```samsung/p3sxeea/p3s:11/RP1A.200720.012/G998BXXU2AUC8:user/release-keys```)
```> adb shell getprop ro.build.fingerprint```
Vulkan driver version using ```gapit```. ```gapit``` is a command line tool you'll find in the folder AGI was installed in. In my case the result is ```"driver_version": 109051904,```
```> ./gapit -log-level Fatal devices -os android | grep driver_version```

**Comment by AlexBogatko** [comment]
@pau-baiget I have the same issue with same device

differences:
Android Version: 12
Host: MacOs
Version 2021-2.1.0:18f18d39314217e73e1404903a4c887e05602293
fingerprint: samsung/o1sxser/o1s:12/SP1A.210812.016/G991BXXU3BUK8:user/release-keys
gapit: "driver_version": 134221824
