### ISSUE TITLE
Support for Oneplus 6T

### ISSUE THREAD

**Issue by AnhadSawhney** [google/agi#936]
Is there any chance of getting support for the Oneplus 6T? It's the only phone I have. It has the Adreno 630 GPU and the android 11 open beta is already out for it.

**Comment by ttanatb** [comment]
Hi all, closing this stale issue.

Support for GPU profiling features require implementation from the device itself, not from additional code in AGI. Moving forward, devices should support GPU profiling features if they have the memory bandwidth to do so, and we've added tests to reduce regressions in subsequent Android releases.
