### ISSUE TITLE
Add support for VK_EXT_descriptor_indexing

### ISSUE THREAD

**Issue by raphlinus** [google/agi#937]
**Environment information:**
 - AGI version: 2021-2.0.0:aad09f92ea8e608b11001aae1f93af3cc1101096
 - Host OS: Windows 10
 If tracing on Android:
 - Device model: Pixel 4
 - Android Version: 11 (RQ3A.210905.001)

**Bug description**
I'm getting an error on profile replay indicating it can't handle queries to descriptor indexing (or subgroup size control).

**Reproduction steps**
Build Android version of [piet-gpu](https://github.com/linebender/piet-gpu). Quick-start on that: install Rust tools, cd piet-gpu, `cargo apk run --example android`

Try to capture a trace (Ctrl-T). Trace capture appears successful, but profile view shows "Replay returned error / Cause: Missing switch case handler for value vulkan.VkStructureType VkStructureType(1000161001)." The [documentation](https://www.khronos.org/registry/vulkan/specs/1.2-extensions/man/html/VkStructureType.html) for that shows that the numeric code is VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_DESCRIPTOR_INDEXING_FEATURES. I am indeed querying for that. I can work around this, disabling that query (and 1000161000 and 1000225000), but it's annoying and it should be valid to do these queries.

**Stacktrace**
Please paste a stacktrace here if it's available.

**Screenshots**

**Additional debugging information**
- Please attach the generated _gapis.log_ and _gapic.log_ files you will find in the temp folder (e.g. /tmp/ on linux).
- If using Android: Please attach a full logcat dump (```adb logcat -d > logcat-full.txt```) that contains logs since AGI was started.

I can put logs if requested, but I think this should be pretty clear.

![agi-missing-switch](https://user-images.githubusercontent.com/242367/135318864-e7585a3f-5623-426e-b06c-da5bb734f7ce.PNG)

**Comment by pmuetschard** [comment]
AGI does not yet support `VK_EXT_descriptor_indexing`. It is core in 1.2, so we will be adding support in the near future.

Make sure you have the `Hide Unknown Extensions` checkbox checked, so that AGI hides extensions supported by the device, but not by AGI from the application during tracing. This option will be cleaned up in the next release.

**Comment by kocdemir** [comment]
Hi, we've added support for this extension with PR #1154 a while ago. You can use the latest dev release (https://github.com/google/agi-dev-releases/releases/tag/v3.2.0-dev-20220913) to check if it works for your use case, and report any issues to be fixed before the next public release.
Thanks

**Comment by kocdemir** [comment]
Closing this one as the feature is available in developer releases and soon will be available with the public release as well. Please reopen or post a new issue if you encounter any issues. 
Thanks
