### ISSUE TITLE
Support for Xiaomi Redmi Note 7

### ISSUE THREAD

**Issue by PjLovePb** [google/agi#947]
**Environment information:**
 - AGI version: 2021-2.0.0:aad09f92ea8e608b11001aae1f93af3cc1101096
 - Host OS: [e.g. Linux]
 If tracing on Android: 
 - Device model:Xiaomi Redmi Note 7 -Android 9 API 28 -Qualcomm Adreno(TM) 512
 - Android Version :9

**Bug description**
Bug description
device support validation failed

Steps to reproduce:
Take a new trace
![image](https://user-images.githubusercontent.com/40516128/136640604-8f9fe6a4-e485-4d04-a416-557976d8ecfa.png)

**Comment by happyHou** [comment]
https://developer.android.com/agi/supported-devices

**Comment by AstroWYH** [comment]
我想问下，你

**Comment by AstroWYH** [comment]
请问一下，我手机型号是支持的，但直接显示这个界面是为什么呢？是windows版本，adb shell可以正常连接到手机。
![image](https://user-images.githubusercontent.com/94472801/187609804-2b3fc714-1083-47f7-be6a-f4c0707be1a3.png)

**Comment by ttanatb** [comment]
Hi all, closing this stale issue.

Support for GPU profiling features require implementation from the device itself, not from additional code in AGI. Moving forward, devices should support GPU profiling features if they have the memory bandwidth to do so, and we've added tests to reduce regressions in subsequent Android releases.
