### ISSUE TITLE
The screenshot of Pubg game can't be display normally

### ISSUE THREAD

**Issue by chiminqiang** [google/agi#977]
**Environment information:**
 - AGI version: 2.1.0
 - Host OS: windows
 If tracing on Android:
 - Device model: OPPO Reno6 Pro+
 - Android Version: Android 11

**Bug description**
after replay with Pubg game trace and save image to a png file, this png file can't display normally in windows.

**Reproduction steps**
1. capture trace of  pubg game(the game name is "和平精英", the package name is "com.tencent.tmgp.pubgmhd".
2. replay this trace and save the image to a png file in framebuffer view.
3. this png file don't have the suffix, and i add ".png" suffix to this file, it still can't be display normally

**Stacktrace**
Please paste a stacktrace here if it's available.

**Screenshots**

**Additional debugging information**
- Please attach the generated _gapis.log_ and _gapic.log_ files you will find in the temp folder (e.g. /tmp/ on linux).
could you tell me where is the log file location in windows?
- If using Android: Please attach a full logcat dump (```adb logcat -d > logcat-full.txt```) that contains logs since AGI was started
![agi_pubg](https://user-images.githubusercontent.com/68411660/141922385-9ef0e9ab-d337-412c-8e51-6901832bfb7b.png)
[android_log.txt](https://github.com/google/agi/files/7543456/android_log.txt)
![open the png file](https://user-images.githubusercontent.com/68411660/141922400-a6e83461-97d0-4eba-8a3e-c91683191859.png)
![replay](https://user-images.githubusercontent.com/68411660/141922401-b95e0ee7-ffdf-4252-b65d-e3200a756646.png)
![save image to file](https://user-images.githubusercontent.com/68411660/141922407-82b43858-8a82-4480-bd2d-cb66fd9b411a.png)

**Comment by chiminqiang** [comment]
[gapic.log](https://github.com/google/agi/files/7544563/gapic.log)
[gapis.log](https://github.com/google/agi/files/7544564/gapis.log)

I've found the gapic and gapis log, and attached them.
Thanks.

**Comment by chiminqiang** [comment]
@yalcinmelihyasin hi, could you share me the status of this issue? is it fixed in the latest version?

**Comment by pmuetschard** [comment]
It looks like the image has an alpha channel of all zeros. In the framebuffer view, if that happens, we automatically disable alpha, but when saving the file, we preserve the alpha channel. Can you open the image in an image editor and disable the alpha channel to see if indeed that is the case?
