### ISSUE TITLE
Support for some devices

### ISSUE THREAD

**Issue by ronanbel** [google/agi#989]
Hi, I'm working in a (big) game dev company, I would like to use Android GUP Inspector, with some Android 11 (API 30) devices currently not supported. (Poco X3, Samsung SM-T500)
Would it be possible for me to change part of the code to test if I can validate these devices by myself ?

**Comment by ttanatb** [comment]
Hi all, closing this stale issue.

Support for GPU profiling features require implementation from the device itself, not from additional code in AGI. Moving forward, devices should support GPU profiling features if they have the memory bandwidth to do so, and we've added tests to reduce regressions in subsequent Android releases.
